<script setup>
import TripPhotoUpload from './TripPhotoUpload.vue';
const model = defineModel({ type: Object, required: true });
defineProps({ disabled: Boolean });
const emit = defineEmits(['busy']);
const groups = [
    { key: 'highlights', title: 'Highlight perjalanan', help: 'Aktivitas unggulan yang membantu pelanggan mengenali trip.', fields: { title: 'Nama aktivitas', time: 'Hari & waktu', location: 'Lokasi', description: 'Deskripsi aktivitas' } },
    { key: 'destinations', title: 'Destinasi & rute', help: 'Mengisi kartu destinasi, preview rute, dan tombol peta pada halaman publik.', fields: { name: 'Nama destinasi', subtitle: 'Ringkasan destinasi', time: 'Hari & waktu', activity: 'Aktivitas', note: 'Catatan kunjungan', coordinates: 'Koordinat destinasi (latitude, longitude)' } },
    { key: 'itineraryDays', title: 'Itinerary per hari', help: 'Isi satu aktivitas per baris, lengkap dengan waktunya.', fields: { day: 'Hari (contoh: Hari 1)', meals: 'Konsumsi yang tersedia', activities: 'Daftar aktivitas, satu per baris' } },
    { key: 'facilityDetails', title: 'Fasilitas paket', help: 'Cantumkan fasilitas yang benar-benar disediakan.', fields: { title: 'Nama fasilitas', category: 'Kategori', note: 'Detail fasilitas' } },
    { key: 'facilities', title: 'Ikon fasilitas di samping harga', help: 'Ringkasan singkat fasilitas pada kartu pemesanan publik.', fields: { label: 'Label fasilitas' } },
    { key: 'faqs', title: 'Pertanyaan umum', help: 'Jawab pertanyaan tentang ketentuan, persiapan, dan kebijakan trip.', fields: { question: 'Pertanyaan', answer: 'Jawaban' } },
];
const add = group => model.value[group.key].push({ ...Object.fromEntries(Object.keys(group.fields).map(key => [key, key === 'activities' ? [] : ''])), ...(['highlights', 'facilities'].includes(group.key) ? { icon: 'Compass' } : {}), ...(group.key === 'highlights' ? { images: [] } : {}) });
const icons = { Compass: 'Aktivitas / Jelajah', MapPin: 'Destinasi', BedDouble: 'Penginapan', Utensils: 'Makanan', Camera: 'Dokumentasi', ShieldCheck: 'Keamanan / P3K', Users: 'Pemandu', Star: 'Unggulan', CalendarDays: 'Jadwal' };
const lines = value => value.split('\n');
</script>
<template>
    <div class="space-y-8">
        <section v-for="group in groups" :key="group.key" class="min-w-0 border-t border-slate-100 pt-7">
            <div class="mb-4 flex flex-wrap items-start justify-between gap-3"><div><h3 class="font-bold text-[#103b60]">{{ group.title }}</h3><p class="mt-1 text-sm text-slate-500">{{ group.help }}</p></div><button type="button" :disabled="disabled" class="panel-secondary" @click="add(group)">+ Tambah</button></div>
            <p v-if="!model[group.key].length" class="rounded-lg bg-slate-50 p-4 text-sm text-slate-500">Belum ditambahkan. Bagian ini tampil di detail trip setelah diisi.</p>
            <article v-for="(item, index) in model[group.key]" :key="index" class="mb-4 min-w-0 rounded-xl border border-slate-200 p-4">
                <div class="mb-4 flex justify-between text-xs font-semibold"><span>{{ group.title }} {{ index + 1 }}</span><button type="button" :disabled="disabled" class="text-rose-600" @click="model[group.key].splice(index, 1)">Hapus</button></div>
                <div class="grid min-w-0 gap-4 sm:grid-cols-2"><label v-for="(label, key) in group.fields" :key="key" class="grid min-w-0 gap-2 text-xs font-semibold text-slate-600" :class="['description', 'answer', 'activities', 'note'].includes(key) ? 'sm:col-span-2' : ''">{{ label }}<textarea v-if="key === 'activities'" :value="item[key].join('\n')" rows="5" class="panel-input [overflow-wrap:anywhere]" :disabled="disabled" @input="item[key] = lines($event.target.value)"></textarea><textarea v-else-if="['description', 'answer', 'note'].includes(key)" v-model="item[key]" rows="3" class="panel-input [overflow-wrap:anywhere]" :disabled="disabled"></textarea><input v-else v-model="item[key]" class="panel-input" :disabled="disabled" /></label></div>
                <label v-if="['highlights', 'facilities'].includes(group.key)" class="mt-4 grid gap-2 text-xs font-semibold">Ikon di halaman publik<select v-model="item.icon" class="panel-input" :disabled="disabled"><option v-for="(label, icon) in icons" :key="icon" :value="icon">{{ label }}</option></select></label>
                <label v-if="group.key === 'destinations'" class="mt-4 grid gap-2 text-xs font-semibold">Foto destinasi dari galeri<select v-model="item.image_url" class="panel-input" :disabled="disabled"><option value="">Tanpa foto</option><option v-for="(photo, photoIndex) in model.detail.images.filter(Boolean)" :key="photo" :value="photo">Foto {{ photoIndex + 1 }}</option></select></label>
                <div v-if="group.key === 'highlights'" class="mt-4"><p class="mb-2 text-xs font-semibold">Foto slider highlight (pilih satu atau beberapa foto galeri)</p><div class="grid grid-cols-3 gap-2 sm:grid-cols-5"><label v-for="(photo, photoIndex) in model.detail.images.filter(Boolean)" :key="photo" class="relative cursor-pointer overflow-hidden rounded-lg border border-slate-200"><img :src="photo" alt="" class="aspect-square w-full object-cover" /><span class="flex items-center gap-2 p-2 text-xs"><input v-model="item.images" type="checkbox" :value="photo" :disabled="disabled" />Foto {{ photoIndex + 1 }}</span></label></div><p class="mt-2 text-xs text-slate-500">Foto yang dipilih akan tampil di slider kartu highlight.</p></div>
            </article>
        </section>
        <section class="grid gap-5 border-t border-slate-100 pt-7 sm:grid-cols-2"><label v-for="(label, key) in { included: 'Termasuk dalam harga', excluded: 'Tidak termasuk dalam harga', packingItems: 'Perlengkapan yang perlu dibawa' }" :key="key" class="grid gap-2 text-sm font-semibold text-[#103b60]">{{ label }}<span class="text-xs font-normal text-slate-500">Satu item per baris. Kosongkan jika tidak ada.</span><textarea :value="model[key].join('\n')" rows="5" class="panel-input [overflow-wrap:anywhere]" :disabled="disabled" @input="model[key] = lines($event.target.value)"></textarea></label></section>
        <section class="border-t border-slate-100 pt-7"><div class="mb-4 flex flex-wrap justify-between gap-3"><div><h3 class="font-bold text-[#103b60]">Panorama 360° <span class="text-xs font-normal text-slate-400">Opsional</span></h3><p class="mt-1 text-sm text-slate-500">Unggah foto panorama equirectangular 2:1, bukan foto biasa.</p></div><button type="button" class="panel-secondary" :disabled="disabled" @click="model.panoramas.push({ title: '', label: '', image_url: '' })">+ Tambah panorama</button></div><div class="grid gap-4 sm:grid-cols-2"><article v-for="(item, index) in model.panoramas" :key="index" class="min-w-0"><label class="mb-3 grid gap-2 text-xs font-semibold">Nama lokasi<input v-model="item.title" class="panel-input" :disabled="disabled" /></label><label class="mb-3 grid gap-2 text-xs font-semibold">Keterangan spot<input v-model="item.label" class="panel-input" :disabled="disabled" /></label><TripPhotoUpload v-model="item.image_url" label="Foto panorama" :disabled="disabled" @busy="emit('busy', $event)" /><button type="button" class="mt-2 text-xs text-rose-600" :disabled="disabled" @click="model.panoramas.splice(index, 1)">Hapus panorama</button></article></div></section>
    </div>
</template>
