<script setup>
import { Head, Link, useForm, usePage } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import MainNavigation from '../Components/Shared/MainNavigation.vue';
const props = defineProps({ booking: Object, gatewayReady: Boolean });
const form = useForm({ reason: '' });
const action = useForm({});
const page = usePage();
const money = n => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n);
</script>
<template>
    <Head :title="booking.reference" /><MainNavigation /><main class="mx-auto max-w-4xl px-5 py-9"><Link :href="route('account')" class="text-xs font-semibold text-blue-600">← Kembali ke pemesanan</Link><h1 class="mt-5 text-2xl font-bold text-[#17345e]">{{ booking.trip.title }}</h1><p class="mt-2 text-xs text-slate-500">{{ booking.reference }}</p><p v-if="page.props.flash?.success" class="mt-4 rounded-lg bg-emerald-50 p-3 text-sm text-emerald-700">{{ page.props.flash.success }}</p><p v-for="(error, key) in page.props.errors" :key="key" class="mt-3 text-sm text-rose-600">{{ error }}</p>
        <div class="mt-6 grid items-start gap-5 md:grid-cols-[1fr_300px]"><section class="panel-surface p-6"><dl class="grid gap-5 sm:grid-cols-2"><div v-for="(value, label) in { Status: booking.status, Peserta: booking.participants, Berangkat: booking.trip.departure_date.slice(0,10), Selesai: booking.trip.end_date.slice(0,10), 'Titik kumpul': booking.trip.meeting_point, Vendor: booking.vendor.name, 'Kontak vendor': booking.vendor.phone, 'Nama pemesan': booking.contact_name }" :key="label"><dt class="text-xs text-slate-400">{{ label }}</dt><dd class="mt-1 text-sm font-semibold">{{ value }}</dd></div></dl><h2 class="mt-7 text-sm font-bold">Itinerary</h2><p class="mt-3 whitespace-pre-wrap text-sm leading-7 text-slate-500">{{ booking.trip.itinerary }}</p></section><aside class="panel-surface p-5"><h2 class="font-bold">Rincian pembayaran</h2><dl class="mt-5 space-y-3 text-xs"><div class="flex justify-between"><dt>Subtotal</dt><dd>{{ money(booking.subtotal) }}</dd></div><div class="flex justify-between"><dt>Diskon</dt><dd>{{ money(booking.discount) }}</dd></div><div class="flex justify-between border-t border-slate-100 pt-4 text-sm font-bold"><dt>Total</dt><dd>{{ money(booking.total) }}</dd></div></dl><p class="mt-4 text-xs text-slate-500">Pembayaran: {{ booking.payment?.status }}</p><template v-if="booking.status === 'awaiting_payment'"><p class="mt-3 text-xs text-slate-400">Batas pembayaran: {{ new Date(booking.expires_at).toLocaleString('id-ID') }}</p><button :disabled="action.processing || !gatewayReady" class="panel-primary mt-5 w-full" @click="action.post(route('bookings.checkout', booking.id))">Lanjut pembayaran</button><p v-if="!gatewayReady" class="mt-2 text-xs leading-5 text-amber-700">Pembayaran online belum aktif. Hubungi dukungan untuk informasi pesanan.</p><button class="panel-secondary mt-2 w-full" :disabled="action.processing" @click="action.post(route('bookings.cancel', booking.id))">Batalkan pesanan</button></template></aside></div>
        <form v-if="['paid', 'confirmed', 'ongoing', 'completed'].includes(booking.status) && !booking.refund" class="panel-surface mt-5 p-6" @submit.prevent="form.post(route('bookings.refund', booking.id))"><h2 class="text-sm font-bold">Ajukan pengembalian dana</h2><textarea v-model="form.reason" required minlength="10" rows="3" class="panel-input mt-4" placeholder="Jelaskan alasan pengajuan"></textarea><button :disabled="form.processing" class="panel-secondary mt-3">Kirim permintaan refund</button></form><p v-if="booking.refund" class="mt-5 rounded-lg bg-blue-50 p-4 text-sm text-blue-700">Status refund: {{ booking.refund.status }}</p>
    </main>
</template>

