<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import { Link, router, useForm, usePage } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import { CheckCircle2, Clock3, Copy, Download, LockKeyhole, RefreshCw } from 'lucide-vue-next';
import CheckoutLayout from '../Components/Shared/CheckoutLayout.vue';
import CheckoutSummary from '../Components/Shared/CheckoutSummary.vue';
import PaymentMethodPicker from '../Components/Shared/PaymentMethodPicker.vue';
const props = defineProps({ kind: String, order: Object, paymentMethods: Array, paymentPreferences: Object, corporateWorkspaceUrl: String, gatewayReady: Boolean, serverNow: String });
const page = usePage();
const isTrip = computed(() => props.kind === 'trip');
const payment = computed(() => props.order.payment);
const selected = ref(payment.value.method || props.paymentMethods.find(method => method.id === props.paymentPreferences?.primary && method.enabled)?.id || '');
const form = useForm({ method: selected.value });
const check = useForm({});
const copied = ref('');
const now = ref(Date.parse(props.serverNow));
let tick; let polling; let anchor = performance.now(); let server = Date.parse(props.serverNow);
watch(() => props.serverNow, value => { server = Date.parse(value); anchor = performance.now(); now.value = server; });
const remaining = computed(() => Math.max(0, Math.floor((Date.parse(props.order.expires_at) - now.value)/1000)));
const countdown = computed(() => `${String(Math.floor(remaining.value/60)).padStart(2,'0')}:${String(remaining.value%60).padStart(2,'0')}`);
const hasInstructions = computed(() => Object.keys(payment.value.instructions || {}).length > 0);
const pending = computed(() => props.order.status === 'awaiting_payment' && payment.value.status === 'pending');
const paid = computed(() => payment.value.status === 'paid');
const method = computed(() => props.paymentMethods.find(item => item.id === payment.value.method));
const detailsUrl = computed(() => props.corporateWorkspaceUrl || route(isTrip.value ? 'bookings.show' : 'souvenirs.orders.show', props.order.id));
const charge = () => { form.method = selected.value; form.post(route('checkout.charge', { type: props.kind, id: props.order.id })); };
const checkStatus = () => check.post(route('checkout.check', { type: props.kind, id: props.order.id }), { preserveScroll: true });
const copy = async value => { try { await navigator.clipboard.writeText(value); copied.value = 'Kode disalin'; } catch { copied.value = 'Salin kode yang ditampilkan secara manual.'; } };
const codes = computed(() => Object.entries(payment.value.instructions || {}).filter(([key]) => ['va_number','payment_code','bill_key','biller_code'].includes(key)));
const codeLabels = { va_number: 'Nomor virtual account', payment_code: 'Kode pembayaran', bill_key: 'Kode pembayaran', biller_code: 'Kode perusahaan' };
const guide = computed(() => {
    if (['alfamart','indomaret'].includes(payment.value.method)) return ['Datangi gerai yang sesuai dengan metode pembayaranmu.', 'Sampaikan pembayaran Midtrans dan tunjukkan kode pembayaran kepada kasir.', 'Periksa nominal sebelum membayar. Jika ada biaya layanan gerai, konfirmasikan kepada kasir.', 'Simpan struk. Status pesanan diperbarui setelah pembayaran diverifikasi.'];
    if (payment.value.method === 'bca') return ['Buka kanal BCA dan pilih pembayaran BCA Virtual Account.', 'Masukkan nomor virtual account pesanan ini.', 'Pastikan nama penerima dan nominal sesuai, lalu konfirmasi pembayaran.', 'Kembali ke halaman ini untuk melihat status pesanan.'];
    if (payment.value.method === 'mandiri') return ['Buka kanal Mandiri dan pilih pembayaran tagihan / multipayment.', 'Masukkan kode perusahaan dan kode pembayaran yang ditampilkan.', 'Periksa nominal sebelum mengonfirmasi pembayaran.', 'Simpan bukti pembayaran dan periksa status pesanan.'];
    return ['Buka aplikasi dompet digital yang kamu pilih.', 'Pindai QR pembayaran, atau gunakan tombol buka aplikasi jika tersedia.', 'Periksa nominal dan konfirmasi pembayaran di aplikasi.', 'Kembali ke halaman ini. Status diperbarui setelah verifikasi pembayaran.'];
});
const download = () => { const text = [`TapakLokal · ${props.order.reference}`, method.value?.name, ...codes.value.map(([key,value]) => `${codeLabels[key]}: ${value}`), `Total: ${props.order.total}`, `Batas waktu: ${props.order.expires_at}`, ...guide.value].join('\n'); const blob = new Blob([text], { type: 'text/plain;charset=utf-8' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = `${props.order.reference}-pembayaran.txt`; link.click(); URL.revokeObjectURL(url); };
onMounted(() => { tick = window.setInterval(() => { now.value = server + performance.now() - anchor; },1000); polling = window.setInterval(() => { if (pending.value && document.visibilityState === 'visible' && hasInstructions.value) router.reload({ only: ['order','navigation','serverNow'], preserveScroll: true }); },20000); });
onBeforeUnmount(() => { clearInterval(tick); clearInterval(polling); });
</script>
<template>
    <CheckoutLayout :title="paid ? 'Pembayaran terverifikasi' : hasInstructions ? 'Selesaikan pembayaran' : 'Pilih cara pembayaran'" :subtitle="paid ? 'Pesanan tercatat di akunmu. Pantau konfirmasi vendor dari detail pesanan.' : hasInstructions ? 'Selesaikan pembayaran sebelum instruksi berakhir.' : 'Pilih metode pembayaran yang ingin kamu gunakan.'" :step="paid ? 3 : 2" :back-url="detailsUrl">
        <div v-if="pending && (hasInstructions || payment.checkout_url)" class="flex flex-wrap items-center justify-between gap-3 rounded-xl bg-[#0175ea] px-6 py-4 text-sm font-semibold text-white"><span class="flex items-center gap-2"><Clock3 class="size-5" />{{ remaining ? 'Batas waktu pembayaran' : 'Batas waktu telah berakhir' }}</span><span class="rounded-lg bg-white/15 px-3 py-1 font-mono text-lg" role="timer" aria-label="Sisa waktu pembayaran">{{ countdown }}</span></div>
        <p v-if="page.props.flash?.success" role="status" class="rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-800">{{ page.props.flash.success }}</p><p v-if="page.props.flash?.error" role="alert" class="rounded-xl bg-red-50 p-4 text-sm text-red-700">{{ page.props.flash.error }}</p><div v-if="Object.keys(form.errors).length" role="alert" class="rounded-xl bg-red-50 p-4 text-sm text-red-700"><p v-for="(error,field) in form.errors" :key="field">{{ error }}</p></div>
        <section v-if="paid" class="rounded-2xl border border-emerald-200 bg-white p-8"><CheckCircle2 class="size-12 text-emerald-600" /><h2 class="mt-5 text-xl font-extrabold">Terima kasih, pembayaranmu sudah diterima.</h2><p class="mt-3 text-sm leading-7 text-slate-600">Vendor menerima pembaruan pesanan ini. Rincian perjalanan atau pengiriman, chat, dan bukti transaksi tersedia dari akun traveler.</p><Link :href="detailsUrl" class="mt-6 inline-flex min-h-12 items-center rounded-xl bg-[#0175ea] px-5 text-sm font-bold text-white">Lihat detail pesanan</Link></section>
        <section v-else-if="!pending || !remaining" class="rounded-2xl border border-slate-200 bg-white p-8"><h2 class="text-lg font-extrabold">{{ payment.status === 'reconciliation_required' ? 'Pembayaran sedang diperiksa' : !remaining ? 'Batas reservasi sudah berakhir' : 'Pesanan tidak dapat dibayar' }}</h2><p class="mt-3 text-sm leading-7 text-slate-600">Status: {{ order.status }}. Buka detail pesanan untuk menghubungi bantuan atau melihat tindak lanjut.</p><Link :href="detailsUrl" class="mt-5 inline-block font-bold text-blue-600">Buka pesanan</Link></section>
        <section v-else-if="hasInstructions" class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div class="flex flex-wrap items-center justify-between gap-4 border-b border-slate-100 bg-[#edf6ff] p-6"><div><p class="text-xs font-bold uppercase tracking-wide text-blue-600">Instruksi pembayaran</p><h2 class="mt-2 text-lg font-extrabold">{{ method?.name }}</h2></div><button type="button" class="inline-flex min-h-10 items-center gap-2 rounded-lg border border-blue-200 bg-white px-3 text-xs font-bold text-blue-600" @click="download"><Download class="size-4" />Unduh panduan</button></div><div class="p-6"><div v-for="[key,value] in codes" :key="key" class="mb-4 rounded-xl border border-slate-200 bg-slate-50 p-5"><p class="text-xs text-slate-500">{{ codeLabels[key] }}</p><div class="mt-3 flex items-center justify-between gap-4"><p class="break-all font-mono text-xl font-extrabold sm:text-2xl">{{ value }}</p><button type="button" :aria-label="`Salin ${codeLabels[key]}`" class="grid size-11 shrink-0 place-items-center rounded-lg border border-slate-200 bg-white text-blue-600" @click="copy(value)"><Copy class="size-4" /></button></div></div><div v-if="payment.instructions.qr_url && remaining" class="rounded-xl border border-slate-200 p-5 text-center"><img :src="payment.instructions.qr_url" alt="QR pembayaran pesanan dari Midtrans" width="240" height="240" class="mx-auto size-60 max-w-full object-contain" /><p class="mt-4 text-xs leading-6 text-slate-500">Pindai QR ini. Jangan gunakan QR dari pihak lain untuk pesanan yang sama.</p></div><a v-if="payment.instructions.app_url && remaining" :href="payment.instructions.app_url" class="mt-5 block rounded-xl bg-blue-600 px-5 py-3 text-center text-sm font-bold text-white">Buka aplikasi pembayaran</a><p v-if="copied" role="status" class="mt-3 text-xs text-blue-600">{{ copied }}</p><h3 class="mt-7 font-extrabold">Cara membayar</h3><ol class="mt-4 space-y-3 text-sm leading-7 text-slate-600"><li v-for="(item,index) in guide" :key="index" class="flex gap-3"><span class="font-bold text-blue-600">{{ index+1 }}.</span><span>{{ item }}</span></li></ol><div class="mt-7 rounded-xl bg-slate-50 p-5"><h3 class="font-bold">Sudah membayar?</h3><p class="mt-2 text-xs leading-6 text-slate-500">Status mengikuti verifikasi penyedia pembayaran. Tombol ini meminta pemeriksaan ulang pembayaranmu.</p><button type="button" :disabled="check.processing || !gatewayReady" class="mt-4 flex min-h-11 w-full items-center justify-center gap-2 rounded-lg border border-blue-200 bg-white text-sm font-bold text-blue-600 disabled:opacity-50" @click="checkStatus"><RefreshCw class="size-4" />{{ check.processing ? 'Meminta pemeriksaan…' : 'Periksa status pembayaran' }}</button></div></div></section>
        <section v-else class="rounded-2xl border border-slate-200 bg-white p-6 sm:p-7"><p class="mb-5 text-xs leading-6 text-slate-500">Kursi atau stok direservasi sampai {{ new Date(order.expires_at).toLocaleString('id-ID') }}. Instruksi pembayaran dibuat setelah kamu menekan tombol bayar.</p><div class="mb-6 flex flex-wrap items-center justify-between gap-3"><h2 class="text-lg font-extrabold">Bayar dengan metode pilihanmu</h2><span class="flex items-center gap-1.5 text-[11px] text-slate-500"><LockKeyhole class="size-3.5 text-blue-600" />Dikelola Midtrans</span></div><template v-if="payment.checkout_url"><p class="text-sm text-slate-600">Instruksi pembayaran sudah dibuat untuk pesanan ini.</p><a :href="payment.checkout_url" class="mt-5 block rounded-xl bg-blue-600 px-5 py-3 text-center font-bold text-white">Lanjutkan pembayaran yang tersimpan</a></template><template v-else><p v-if="payment.method" class="mb-5 rounded-xl bg-blue-50 p-4 text-sm leading-6 text-blue-800">Permintaan pembayaran sudah dikirim. Coba kembali dengan metode yang sama agar transaksi tidak dibuat ganda.</p><PaymentMethodPicker v-model="selected" :methods="paymentMethods" :preferences="paymentPreferences" :disabled="form.processing || !remaining || !!payment.method" /><p v-if="!gatewayReady" role="status" class="mt-6 rounded-xl bg-amber-50 p-4 text-sm leading-6 text-amber-900">Pembayaran online belum aktif. Pesanan tersimpan di akunmu; hubungi bantuan untuk tindak lanjut.</p><button type="button" :disabled="!paymentMethods.some(item => item.id === selected && item.enabled) || !gatewayReady || form.processing || !remaining" class="mt-7 min-h-12 w-full rounded-xl bg-[#0175ea] px-5 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-50" @click="charge">{{ form.processing ? 'Menyiapkan pembayaran…' : `Bayar dengan ${paymentMethods.find(item => item.id === selected)?.name || 'metode pilihan'}` }}</button><Link :href="route('account.section','wallet')" class="mt-4 block text-center text-xs font-semibold text-blue-600">Kelola metode utama di akun</Link></template></section>
        <template #summary><CheckoutSummary :title="isTrip ? order.trip.title : 'Pesanan oleh-oleh'" :vendor="order.vendor.name" :image="order.trip?.image_url" :reference="order.reference" :date="isTrip ? order.trip.departure_date : order.pickup_date" :end-date="order.trip?.end_date" :participants="isTrip ? order.participants : null" :lines="order.items" :method="isTrip ? null : order.method" :address="isTrip ? order.trip.meeting_point : order.address" :subtotal="order.subtotal" :shipping="order.shipping_fee" :discount="order.discount" :total="order.total" /><section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="text-sm font-bold">Kontak pesanan</h2><p class="mt-3 text-sm">{{ order.contact_name }}</p><p class="mt-2 break-all text-xs text-slate-500">{{ order.contact_email || page.props.auth.user.email }}</p><p class="mt-2 text-xs text-slate-500">{{ order.contact_phone }}</p><Link :href="detailsUrl" class="mt-5 block text-xs font-bold text-blue-600">{{ corporateWorkspaceUrl ? 'Kembali ke workspace perusahaan' : 'Detail pesanan & chat vendor' }}</Link></section></template>
    </CheckoutLayout>
</template>
