<script setup>
import { computed, ref, watch } from 'vue';
import { Link, useForm, usePage } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import { ChevronRight, Mail, Minus, Plus, UserRound, UsersRound, MapPin, Info } from 'lucide-vue-next';
import CheckoutLayout from '../Components/Shared/CheckoutLayout.vue';
import CheckoutSummary from '../Components/Shared/CheckoutSummary.vue';
const props = defineProps({ kind: String, trip: Object, participants: Number, bookingKey: String, travelerProfiles: Array, cartLines: Array, canBook: Boolean, minimumPickup: String });
const page = usePage();
const isTrip = computed(() => props.kind === 'trip');
const user = page.props.auth.user;
const sameAsBooker = ref(true);
const lines = computed(() => (props.cartLines || []).map(line => ({ ...line, name: line.product.name, unit_price: line.product.selling_price })));
const form = useForm({ trip_id: props.trip?.id, participants: props.participants || 1, idempotency_key: props.bookingKey, checkout_flow: true, contact_name: user.name || '', contact_email: user.email || '', contact_phone: user.phone || '', promotion_code: '', special_request: '', traveler_details: [], vendor_id: props.cartLines?.[0]?.product.vendor_id, method: 'pickup', pickup_date: '', address: '', delivery_region: '', delivery_service: '' });
const maxParticipants = computed(() => Math.min(50, Math.max(0, (props.trip?.capacity || 0) - (props.trip?.reserved_seats || 0))));
const canContinue = computed(() => !isTrip.value || (maxParticipants.value >= form.participants && props.canBook));
watch(() => form.participants, count => { form.traveler_details = Array.from({ length: count }, (_, index) => form.traveler_details[index] || { name: index === 0 && sameAsBooker.value ? form.contact_name : '', profile_id: null }); }, { immediate: true });
watch(() => [form.contact_name, sameAsBooker.value], () => { if (sameAsBooker.value && form.traveler_details[0]) { form.traveler_details[0].name = form.contact_name; form.traveler_details[0].profile_id = null; } });
const selectTraveler = (index, event) => { const profile = props.travelerProfiles.find(item => item.id === Number(event.target.value)); if (index === 0) sameAsBooker.value = false; form.traveler_details[index] = { name: profile?.name || '', profile_id: profile?.id || null }; };
const vendorName = computed(() => isTrip.value ? props.trip.vendor.name : props.cartLines?.[0]?.product.vendor.name);
const subtotal = computed(() => isTrip.value ? props.trip.selling_price * form.participants : lines.value.reduce((total,line) => total + line.unit_price * line.quantity, 0));
const pickupAddress = computed(() => [...new Set(lines.value.map(line => line.product.pickup_address).filter(Boolean))].join('\n'));
const pickupOnly = computed(() => lines.value.some(line => line.product.pickup_only || !line.product.delivery_rates?.length));
const shippingOptions = computed(() => (lines.value[0]?.product.delivery_rates || []).filter(rate => lines.value.every(line => line.product.delivery_rates?.some(item => item.region === rate.region && item.service === rate.service))));
const shippingFee = computed(() => form.method === 'pickup' ? 0 : lines.value.reduce((total,line) => total + (line.product.delivery_rates?.find(rate => rate.region === form.delivery_region && rate.service === form.delivery_service)?.fee || 0) * line.quantity, 0));
const selectShipping = event => { const option = shippingOptions.value[Number(event.target.value)]; form.delivery_region = option?.region || ''; form.delivery_service = option?.service || ''; };
const minPickup = computed(() => props.minimumPickup);
const submit = () => { form.transform(data => isTrip.value ? { ...data, vendor_id: undefined, method: undefined, pickup_date: undefined, address: undefined, delivery_region: undefined, delivery_service: undefined } : { ...data, trip_id: undefined, participants: undefined, traveler_details: undefined, special_request: undefined, promotion_code: undefined }).post(route(isTrip.value ? 'bookings.store' : 'souvenirs.orders.create')); };
const backUrl = computed(() => isTrip.value ? route('trips.show', [props.trip.type, props.trip.slug]) : route('souvenirs.cart'));
</script>
<template>
    <CheckoutLayout title="Periksa pesananmu" subtitle="Pastikan detail sudah sesuai sebelum melanjutkan ke pembayaran." :step="1" :back-url="backUrl">
        <form id="review-order" class="space-y-6" @submit.prevent="submit">
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-xs"><div class="flex items-center gap-3 border-b border-slate-100 px-6 py-4"><UserRound class="size-5 text-[#0175ea]" /><div><h2 class="font-extrabold">{{ isTrip ? 'Kontak pemesan' : 'Detail penerima' }}</h2><p class="mt-1 text-xs text-slate-500">Informasi untuk konfirmasi dan komunikasi pesanan.</p></div></div><div class="grid gap-5 p-6 sm:grid-cols-2"><label class="text-xs font-bold sm:col-span-2">Nama lengkap<input v-model="form.contact_name" required maxlength="100" autocomplete="name" class="panel-input mt-2" /></label><label class="text-xs font-bold">Email<input v-model="form.contact_email" required type="email" maxlength="255" autocomplete="email" class="panel-input mt-2" /></label><label class="text-xs font-bold">Nomor telepon / WhatsApp<input v-model="form.contact_phone" required type="tel" maxlength="15" autocomplete="tel" class="panel-input mt-2" placeholder="Contoh: 081234567890" /></label></div></section>
            <section v-if="isTrip" class="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs"><div class="flex flex-wrap items-center justify-between gap-4"><div class="flex items-center gap-3"><UsersRound class="size-5 text-[#0175ea]" /><h2 class="font-extrabold">Peserta perjalanan</h2></div><div class="flex items-center gap-4"><button type="button" :disabled="form.participants <= 1" class="grid size-10 place-items-center rounded-lg border border-slate-200 disabled:opacity-40" aria-label="Kurangi peserta" @click="form.participants--"><Minus class="size-4" /></button><span aria-live="polite" class="font-bold">{{ form.participants }}</span><button type="button" :disabled="form.participants >= maxParticipants" class="grid size-10 place-items-center rounded-lg border border-slate-200 disabled:opacity-40" aria-label="Tambah peserta" @click="form.participants++"><Plus class="size-4" /></button></div></div><label class="mt-5 flex items-center gap-3 text-sm"><input v-model="sameAsBooker" type="checkbox" class="size-4 accent-[#0175ea]" />Pemesan ikut dalam perjalanan</label><div v-for="(traveler,index) in form.traveler_details" :key="index" class="mt-5 rounded-xl bg-[#f5f9ff] p-4"><h3 class="text-xs font-bold">Peserta {{ index + 1 }}</h3><select v-if="travelerProfiles?.length && !(index === 0 && sameAsBooker)" :value="traveler.profile_id || ''" class="panel-input mt-3" :aria-label="`Pilih wisatawan tersimpan untuk peserta ${index+1}`" @change="selectTraveler(index,$event)"><option value="">Isi peserta baru</option><option v-for="profile in travelerProfiles" :key="profile.id" :value="profile.id">{{ profile.name }}</option></select><label class="mt-3 block text-xs font-semibold">Nama sesuai identitas<input v-model="traveler.name" required maxlength="100" :readonly="index === 0 && sameAsBooker" class="panel-input mt-2" /></label></div><Link :href="route('account.section','travelers')" class="mt-4 inline-block text-xs font-semibold text-[#0175ea]">Kelola daftar wisatawan di akun</Link></section>
            <section v-else class="rounded-2xl border border-slate-200 bg-white p-6 shadow-xs"><h2 class="flex items-center gap-3 font-extrabold"><MapPin class="size-5 text-[#0175ea]" />Cara menerima pesanan</h2><div class="mt-5 grid grid-cols-2 gap-3"><label class="cursor-pointer rounded-xl border p-4 text-sm" :class="form.method === 'pickup' ? 'border-blue-500 bg-blue-50' : 'border-slate-200'"><input v-model="form.method" type="radio" value="pickup" class="mr-2 accent-blue-600" />Ambil di tempat</label><label class="rounded-xl border p-4 text-sm" :class="pickupOnly ? 'border-slate-100 text-slate-400' : form.method === 'delivery' ? 'border-blue-500 bg-blue-50' : 'border-slate-200'"><input v-model="form.method" :disabled="pickupOnly" type="radio" value="delivery" class="mr-2 accent-blue-600" />Kirim ke rumah</label></div><template v-if="form.method === 'pickup'"><p class="mt-4 whitespace-pre-line rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600">{{ pickupAddress || 'Lokasi pengambilan belum tersedia.' }}</p><label class="mt-5 block text-xs font-bold">Tanggal pengambilan<input v-model="form.pickup_date" required type="date" :min="minPickup" class="panel-input mt-2" /></label></template><template v-else><label class="mt-5 block text-xs font-bold">Daerah dan layanan pengiriman<select required class="panel-input mt-2" @change="selectShipping"><option value="">Pilih layanan tersedia</option><option v-for="(option,index) in shippingOptions" :key="index" :value="index">{{ option.region }} · {{ option.service }}</option></select></label><label class="mt-5 block text-xs font-bold">Alamat lengkap<textarea v-model="form.address" required minlength="15" maxlength="1000" autocomplete="street-address" rows="3" class="panel-input mt-2" /></label></template></section>
            <section v-if="isTrip" class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="font-extrabold">Permintaan khusus</h2><p class="mt-2 text-xs leading-6 text-slate-500">Tuliskan kebutuhan makanan atau bantuan perjalanan. Pemenuhan perlu dikonfirmasi oleh vendor.</p><textarea v-model="form.special_request" rows="3" maxlength="2000" class="panel-input mt-4" aria-label="Permintaan khusus opsional" /><label class="mt-5 block text-xs font-bold">Kode promo (opsional)<input v-model="form.promotion_code" maxlength="50" class="panel-input mt-2" /></label></section>
            <section class="rounded-2xl border border-slate-200 bg-white p-6"><h2 class="flex items-center gap-3 font-extrabold"><Info class="size-5 text-blue-600" />Sebelum melanjutkan</h2><p class="mt-3 text-sm leading-7 text-slate-600">Periksa jadwal, kontak, dan jumlah pesanan. Setelah pesanan dibuat, kamu memiliki 30 menit untuk membayar. Permintaan pembatalan dan bantuan tersedia dari detail pesanan di akun.</p><label class="mt-5 flex items-start gap-3 text-sm leading-6"><input required type="checkbox" class="mt-1 size-4 shrink-0 accent-blue-600" />Saya sudah memeriksa detail pesanan dan memahami bahwa permintaan khusus perlu dikonfirmasi.</label><p v-if="!canContinue" role="alert" class="mt-4 text-sm text-red-700">Jadwal atau kuota ini sudah tidak tersedia. Silakan pilih perjalanan lain.</p><div v-if="Object.keys(form.errors).length" role="alert" class="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700"><p v-for="(error,field) in form.errors" :key="field">{{ error }}</p></div></section>
        </form>
        <template #summary><CheckoutSummary :title="isTrip ? trip.title : 'Oleh-oleh pilihanmu'" :vendor="vendorName" :image="trip?.image_url" :date="isTrip ? trip.departure_date : form.pickup_date" :end-date="trip?.end_date" :participants="isTrip ? form.participants : null" :lines="isTrip ? [] : lines" :method="isTrip ? null : form.method" :address="isTrip ? trip.meeting_point : form.method === 'pickup' ? pickupAddress : form.address" :subtotal="subtotal" :shipping="shippingFee" :total="subtotal + shippingFee"><p class="mt-5 text-xs leading-6 text-slate-500">Harga, promo, dan ketersediaan diperiksa kembali saat kamu melanjutkan.</p><button type="submit" form="review-order" :disabled="form.processing || !canContinue" class="mt-5 flex min-h-12 w-full items-center justify-center gap-2 rounded-xl bg-[#0175ea] px-4 text-sm font-bold text-white hover:bg-blue-700 disabled:opacity-50">{{ form.processing ? 'Mencatat pesanan…' : 'Lanjut ke pembayaran' }}<ChevronRight class="size-4" /></button></CheckoutSummary></template>
    </CheckoutLayout>
</template>
