<script setup>
import { ref } from 'vue';
import { Link, useForm, router } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import PanelLayout from '../Components/Admin/PanelLayout.vue';
defineProps({ companies:Object, requests:Object, trips:Object, navigation:Array });
const verification = useForm({status:'verified',verification_note:''});
const offer = useForm({trip_id:'',terms:''});
const selectedCompany = ref(null);
const selectedRequest = ref(null);
const search = ref('');
const money = value=>new Intl.NumberFormat('id-ID',{style:'currency',currency:'IDR',maximumFractionDigits:0}).format(value || 0);
function verify(company) { selectedCompany.value=company;verification.reset();verification.clearErrors(); }
function quote(item) { selectedRequest.value=item;offer.reset();offer.clearErrors(); }
</script>
<template><PanelLayout title="Operasional corporate" subtitle="Verifikasi perusahaan, susun penawaran, lalu pantau pemesanan." :navigation="navigation"><section class="panel-surface p-6"><h2 class="text-lg font-bold">Registrasi perusahaan</h2><article v-for="company in companies.data" :key="company.id" class="mt-5 flex flex-wrap items-center justify-between gap-4 border-t border-slate-100 pt-5"><div><p class="font-semibold">{{ company.name }} · {{ company.status }}</p><p class="mt-2 text-sm text-slate-500">{{ company.pic_name }} · {{ company.position }} · {{ company.work_email }} · {{ company.phone }}</p><p class="mt-2 text-xs text-slate-500">Anggaran: {{ company.budget_range }} · Sumber: {{ company.source }} · Persetujuan data {{ company.consented_at.slice(0,10) }}</p></div><button class="panel-secondary" @click="verify(company)">Tinjau perusahaan</button></article><p v-if="!companies.data.length" class="py-10 text-sm text-slate-500">Belum ada registrasi.</p><form v-if="selectedCompany" class="mt-6 rounded-lg border border-slate-200 p-5" @submit.prevent="verification.put(route('admin.corporate.verify',selectedCompany.id),{onSuccess:()=>selectedCompany=null})"><h3 class="font-bold">{{ selectedCompany.name }}</h3><label class="mt-4 block text-xs font-semibold">Hasil verifikasi<select v-model="verification.status" class="panel-input mt-2"><option value="verified">Aktifkan perusahaan</option><option value="rejected">Tolak registrasi</option><option value="suspended">Batasi akses pemesanan</option></select></label><label class="mt-4 block text-xs font-semibold">Catatan verifikasi<textarea v-model="verification.verification_note" required minlength="10" maxlength="2000" rows="3" class="panel-input mt-2" /></label><p v-for="error in verification.errors" :key="error" role="alert" class="mt-3 text-sm text-red-700">{{ error }}</p><button :disabled="verification.processing" class="panel-primary mt-4">Simpan hasil</button></form><nav class="mt-5 flex gap-5 text-xs"><Link v-if="companies.prev_page_url" :href="companies.prev_page_url">Sebelumnya</Link><Link v-if="companies.next_page_url" :href="companies.next_page_url">Berikutnya</Link></nav></section>
<section class="panel-surface mt-7 p-6"><h2 class="text-lg font-bold">Kebutuhan & penawaran</h2><article v-for="item in requests.data" :key="item.id" class="mt-5 border-t border-slate-100 pt-5"><div class="flex flex-wrap justify-between gap-4"><div><p class="font-bold">{{ item.company.name }} · {{ item.title }}</p><p class="mt-2 text-xs text-slate-500">{{ item.destination }} · {{ item.departure_date.slice(0,10) }} – {{ item.end_date.slice(0,10) }} · {{ item.participants }} peserta</p><p class="mt-2 text-xs">Anggaran {{ money(item.budget) }} · {{ item.status }}{{ item.booking ? ' · Pesanan '+item.booking.status : '' }}</p><p class="mt-3 max-w-3xl whitespace-pre-line text-sm leading-6">{{ item.needs }}</p></div><button v-if="['submitted','quoted','approved'].includes(item.status)" class="panel-secondary self-start" @click="quote(item)">{{ item.quote ? 'Revisi penawaran' : 'Buat penawaran' }}</button></div></article><p v-if="!requests.data.length" class="py-10 text-sm text-slate-500">Belum ada pengajuan.</p><nav class="mt-5 flex gap-5 text-xs"><Link v-if="requests.prev_page_url" :href="requests.prev_page_url">Sebelumnya</Link><Link v-if="requests.next_page_url" :href="requests.next_page_url">Berikutnya</Link></nav>
<div v-if="selectedRequest" class="mt-7 rounded-lg border border-slate-200 p-5"><h3 class="font-bold">Penawaran untuk {{ selectedRequest.title }}</h3><p class="mt-3 text-xs leading-6 text-slate-500">Pilih private trip dengan jadwal yang sama dan kuota mencukupi. Vendor menyiapkan trip melalui dashboard, lalu admin menerbitkannya. Revisi membatalkan persetujuan sebelumnya; perusahaan perlu menyetujui ulang.</p><form class="mt-4 flex gap-3" @submit.prevent="router.get(route('admin.corporate'),{search:search},{preserveState:true})"><input v-model="search" aria-label="Cari private trip" placeholder="Cari private trip…" class="panel-input" /><button class="panel-secondary">Cari</button></form><form class="mt-5" @submit.prevent="offer.post(route('admin.corporate.offer',selectedRequest.id),{onSuccess:()=>selectedRequest=null})"><label class="text-xs font-semibold">Paket vendor<select v-model="offer.trip_id" required class="panel-input mt-2"><option value="" disabled>Pilih paket</option><option v-for="trip in trips.data" :key="trip.id" :value="trip.id">{{ trip.title }} · {{ trip.vendor.name }} · {{ trip.departure_date.slice(0,10) }} · {{ money(trip.selling_price) }}/orang</option></select></label><nav class="mt-3 flex gap-4 text-xs"><Link v-if="trips.prev_page_url" :href="trips.prev_page_url" preserve-state>Sebelumnya</Link><Link v-if="trips.next_page_url" :href="trips.next_page_url" preserve-state>Berikutnya</Link></nav><label class="mt-5 block text-xs font-semibold">Fasilitas, ketentuan, dan kebijakan pembatalan<textarea v-model="offer.terms" required minlength="20" maxlength="10000" rows="5" class="panel-input mt-2" /></label><p v-for="error in offer.errors" :key="error" role="alert" class="mt-3 text-sm text-red-700">{{ error }}</p><button :disabled="offer.processing" class="panel-primary mt-4">Kirim penawaran</button></form></div></section></PanelLayout></template>
