<script setup>
import { computed, nextTick, ref } from 'vue';
import AccountExploreBanner from './AccountExploreBanner.vue';
import { Bold, ImagePlus, Italic, List, ArrowLeft, CalendarDays, CheckCircle2, ChevronLeft, ChevronRight, Heart, MapPin, MessageCircle, Plus, Search, Send, Star, Trash2, Users, X } from 'lucide-vue-next';
defineProps({ section: { type: String, required: true } });
const filter = ref('Semua');
const search = ref('');
const favorites = ref([{ id: 1, name: 'Open Trip Bali', type: 'Open Trip', place: 'Bali', price: 'Rp 750.000', image: '1537996194471-e657df975ab4' }, { id: 2, name: 'Private Trip Lombok', type: 'Private Trip', place: 'Lombok', price: 'Rp 1.500.000', image: '1518548419970-58e3b4079ab2' }]);
const visibleFavorites = computed(() => favorites.value.filter((item) => (filter.value === 'Semua' || item.type === filter.value) && item.name.toLowerCase().includes(search.value.toLowerCase())));
const travelers = ref([{ id: 1, name: 'Albnnaardy', relation: 'Diri sendiri' }]);
const travelerSearch = ref('');
const visibleTravelers = computed(() => travelers.value.filter((person) => person.name.toLowerCase().includes(travelerSearch.value.trim().toLowerCase())));
const travelerName = ref('');
const relation = ref('Keluarga');
const dialog = ref(null);
const editing = ref(null);
const openTraveler = (item = null) => { editing.value = item; travelerName.value = item?.name || ''; relation.value = item?.relation || 'Keluarga'; dialog.value.showModal(); };
const saveTraveler = () => { if (!travelerName.value.trim()) { return; } if (editing.value) { editing.value.name = travelerName.value.trim(); editing.value.relation = relation.value; } else { travelers.value.push({ id: Date.now(), name: travelerName.value.trim(), relation: relation.value }); } dialog.value.close(); };
const conversations = ref([{ id: 1, name: 'Partner Trip Bali', subtitle: 'Informasi perjalanan', messages: [{ own: false, text: 'Halo! Ada yang ingin ditanyakan tentang perjalananmu?' }] }, { id: 2, name: 'Tim TapakLokal', subtitle: 'Bantuan pemesanan', messages: [{ own: false, text: 'Selamat datang di pratinjau chat TapakLokal.' }] }]);
const selectedChat = ref(1);
const chat = computed(() => conversations.value.find((item) => item.id === selectedChat.value));
const draft = ref('');
const send = () => { if (!draft.value.trim()) { return; } chat.value.messages.push({ own: true, text: draft.value.trim() }); draft.value = ''; };
const rating = ref(0);
const reviewText = ref('');
const reviewEditor = ref(null);
const reviewImageInput = ref(null);
const reviewImages = ref([]);
const reviews = ref([]);
const reviewError = ref('');
const reviewView = ref('orders');
const reviewOrder = ref(null);
const reviewNotice = ref('');
const reviewPage = ref(1);
const reviewScroll = ref(null);
const reviewPageSize = 4;
const completedOrders = ref([
    { id: 'TL-2025-001', name: 'Pantai Drini', location: 'Gunungkidul, Yogyakarta', date: '24 Sep 2025', image: '1507525428034-b723cf961d3e', reviewed: false },
    { id: 'TL-2025-002', name: 'Open Trip Karimunjawa', location: 'Jepara, Jawa Tengah', date: '12 Agu 2025', image: '1518548419970-58e3b4079ab2', reviewed: false },
    { id: 'TL-2025-003', name: 'Candi Prambanan', location: 'Sleman, Yogyakarta', date: '30 Jul 2025', image: '1537996194471-e657df975ab4', reviewed: true },
    ...['Bromo Sunrise', 'Ranu Kumbolo', 'Pulau Pramuka', 'Kawah Ijen', 'Labuan Bajo', 'Dieng Plateau', 'Raja Ampat', 'Tanjung Lesung', 'Pulau Pari'].map((name, index) => ({
        id: `TL-2025-${String(index + 4).padStart(3, '0')}`,
        name: `Open Trip ${name}`,
        location: ['Probolinggo, Jawa Timur', 'Lumajang, Jawa Timur', 'Kepulauan Seribu', 'Banyuwangi, Jawa Timur', 'Nusa Tenggara Timur'][index % 5],
        date: `${20 - index} Jul 2025`,
        image: ['1500534314209-a25ddb2bd429', '1501179691627-eeaa65ea017c', '1518548419970-58e3b4079ab2', '1478827536114-da961b7e8b80', '1507525428034-b723cf961d3e'][index % 5],
        reviewed: index % 4 === 0,
    })),
]);
const reviewPageCount = computed(() => Math.max(1, Math.ceil(completedOrders.value.length / reviewPageSize)));
const reviewStart = computed(() => (reviewPage.value - 1) * reviewPageSize);
const visibleReviewOrders = computed(() => completedOrders.value.slice(reviewStart.value, reviewStart.value + reviewPageSize));
const goReviewPage = (page) => { reviewPage.value = Math.max(1, Math.min(page, reviewPageCount.value)); reviewScroll.value?.scrollTo({ top: 0, behavior: 'smooth' }); };
const openReview = (order) => {
    reviewOrder.value = order;
    rating.value = 0;
    reviewText.value = '';
    reviewImages.value = [];
    reviewError.value = '';
    reviewNotice.value = '';
    reviewView.value = 'form';
    nextTick(() => { if (reviewEditor.value) { reviewEditor.value.innerHTML = ''; } });
};
const formatReview = (command) => { reviewEditor.value?.focus(); document.execCommand(command, false); reviewText.value = reviewEditor.value?.innerText.trim() ?? ''; };
const updateReviewText = () => { reviewText.value = reviewEditor.value?.innerText.trim() ?? ''; };
const addReviewImages = (event) => {
    const files = Array.from(event.target.files ?? []);
    const valid = files.filter((file) => ['image/jpeg', 'image/png', 'image/webp'].includes(file.type) && file.size <= 2 * 1024 * 1024).slice(0, 5 - reviewImages.value.length);
    if (valid.length !== files.length) { reviewError.value = 'Foto harus JPG, PNG, atau WebP maksimal 2 MB. Maksimal 5 foto.'; }
    reviewImages.value.push(...valid.map((file) => ({ id: `${file.name}-${file.lastModified}`, url: URL.createObjectURL(file), name: file.name })));
    event.target.value = '';
};
const removeReviewImage = (image) => { reviewImages.value = reviewImages.value.filter((item) => item.id !== image.id); URL.revokeObjectURL(image.url); };
const saveReview = () => {
    if (!rating.value) { reviewError.value = 'Pilih rating terlebih dahulu.'; return; }
    if (reviewText.value.trim().length < 10) { reviewError.value = 'Tulis ulasan minimal 10 karakter.'; return; }
    reviews.value.unshift({ id: Date.now(), orderId: reviewOrder.value.id, orderName: reviewOrder.value.name, rating: rating.value, text: reviewText.value.trim(), images: reviewImages.value.map((image) => image.url) });
    reviewOrder.value.reviewed = true;
    reviewNotice.value = `Ulasan untuk ${reviewOrder.value.name} tersimpan pada pratinjau.`;
    reviewView.value = 'orders';
    rating.value = 0;
    reviewText.value = '';
    reviewImages.value = [];
    reviewError.value = '';
};
const subject = ref('');
const category = ref('Pemesanan');
const helpText = ref('');
const tickets = ref([]);
const saveTicket = () => {
    if (!subject.value.trim() || helpText.value.trim().length < 10) { return; }
    tickets.value.unshift({ id: Date.now(), subject: subject.value.trim(), category: category.value, text: helpText.value.trim(), date: 'Baru saja' });
    subject.value = '';
    helpText.value = '';
};
const control = 'w-full rounded-xl border border-[#dce5f0] bg-white px-3 py-3 text-sm outline-[#078cff]';
const primary = 'rounded-lg bg-[#1045a5] px-4 py-2.5 text-xs font-semibold text-white transition hover:bg-[#083788] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#078cff]';
</script>

<template>
    <section class="text-[#26364d]">
        <h2 :class="['OT & OP Favorit', 'Daftar Wisatawan', 'Rating & Ulasan', 'Pesan Bantuan'].includes(section) ? 'text-sm font-extrabold text-[#183660]' : 'text-xl font-extrabold tracking-tight'">{{ section }}</h2>
        <p class="mt-1 text-[11px] leading-5 text-slate-500">{{ { 'OT & OP Favorit': 'Simpan inspirasi perjalanan dan temukan kembali trip pilihanmu.', 'Daftar Wisatawan': 'Kelola daftar peserta untuk memudahkan pemesanan berikutnya.', Chat: 'Percakapan dengan partner dan tim TapakLokal.', 'Rating & Ulasan': 'Bagikan ulasan setelah perjalanan selesai untuk membantu traveler lainnya.', 'Pesan Bantuan': 'Ceritakan kendalamu agar lebih mudah ditangani.' }[section] }}</p>

        <template v-if="section === 'OT & OP Favorit'">
            <div class="mt-4 rounded-2xl border border-[#e1eaf5] bg-white p-4 shadow-[0_4px_20px_rgba(23,75,120,0.04)]">
                <label class="flex h-10 items-center gap-2 rounded-xl border border-[#e1eaf5] px-3 focus-within:border-[#078cff] focus-within:ring-2 focus-within:ring-sky-100"><Search class="size-4 text-[#078cff]" /><input v-model="search" type="search" placeholder="Cari perjalanan favoritmu…" aria-label="Cari trip favorit" class="min-w-0 flex-1 bg-transparent text-xs outline-none" /></label>
                <div class="mt-3 flex flex-wrap gap-1"><button v-for="item in ['Semua', 'Open Trip', 'Private Trip']" :key="item" type="button" class="min-h-8 rounded-full px-3 py-1.5 text-[10px] font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-[#3E7BEF]" :class="filter === item ? 'bg-[#3E7BEF] text-white shadow-sm' : 'bg-[#f8fafc] text-slate-500 hover:bg-[#edf4ff]'" :aria-pressed="filter === item" @click="filter = item">{{ item }}</button></div>
            </div>
            <section class="mt-4 overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]" aria-label="Daftar favorit">
                <div class="flex items-center justify-between border-b border-slate-100 px-4 py-3"><h3 class="flex items-center gap-2 text-xs font-semibold text-[#183660]"><Heart class="size-4 text-[#3E7BEF]" />Pilihan favoritmu</h3><span class="rounded-full bg-[#edf4ff] px-2.5 py-1 text-[10px] text-[#3E7BEF]" aria-live="polite">{{ visibleFavorites.length }} tersimpan</span></div>
                <div tabindex="0" role="region" aria-label="Daftar favorit, dapat digulir" class="max-h-[520px] overflow-y-auto overscroll-contain bg-[#f8fafc] p-3 sm:p-4 [scrollbar-width:thin] [scrollbar-color:#b9d5fa_transparent]">
                    <div class="grid gap-3 sm:grid-cols-2"><article v-for="item in visibleFavorites" :key="item.id" class="group overflow-hidden rounded-xl border border-[#e1eaf5] bg-white transition duration-200 hover:border-[#aacbff] hover:shadow-md"><div class="relative h-36 overflow-hidden"><img :src="`https://images.unsplash.com/photo-${item.image}?auto=format&fit=crop&w=640&q=85`" :alt="item.name" loading="lazy" class="size-full object-cover transition-transform duration-300 group-hover:scale-105 motion-reduce:transform-none" /><div class="pointer-events-none absolute inset-0 bg-gradient-to-t from-slate-900/40 to-transparent"></div><span class="absolute bottom-3 left-3 rounded-full bg-white/95 px-2.5 py-1 text-[9px] font-semibold text-[#3E7BEF]">{{ item.type }}</span><button type="button" class="absolute right-3 top-3 rounded-full bg-white p-2 text-rose-500 shadow-sm transition-colors hover:bg-rose-50 focus-visible:outline-2 focus-visible:outline-[#3E7BEF]" :aria-label="`Hapus ${item.name} dari favorit`" @click="favorites = favorites.filter((favorite) => favorite.id !== item.id)"><Heart class="size-4 fill-current" /></button></div><div class="p-4"><h3 class="text-xs font-bold text-[#183660]">{{ item.name }}</h3><p class="mt-1.5 text-[11px] text-slate-500">{{ item.place }}</p><div class="mt-4 border-t border-slate-100 pt-3"><p class="text-[9px] text-slate-400">Mulai dari</p><p class="mt-1 text-sm font-bold text-[#078cff]">{{ item.price }} <span class="text-[9px] font-normal text-slate-400">/ orang</span></p></div></div></article></div>
                    <div v-if="!visibleFavorites.length" class="rounded-xl border border-[#e1eaf5] bg-white px-4 py-10 text-center"><Heart class="mx-auto size-8 text-blue-200" /><p class="mt-3 text-xs font-semibold text-[#183660]">Belum ada trip favorit yang sesuai.</p><p class="mt-2 text-[11px] text-slate-500">Coba kata kunci atau jenis perjalanan lainnya.</p></div>
                </div>
            </section>
            <AccountExploreBanner />
        </template>

        <template v-else-if="section === 'Daftar Wisatawan'">
            <div class="mt-4 flex flex-wrap items-center justify-between gap-4 overflow-hidden rounded-2xl border border-[#c7e5f5] bg-gradient-to-br from-[#edf4ff] via-white to-[#dff4fa] p-5">
                <div class="flex items-center gap-3"><span class="grid size-11 shrink-0 place-items-center rounded-xl border border-white bg-white/80 text-[#3E7BEF]"><Users class="size-5" /></span><div><h3 class="text-sm font-bold text-[#183660]">Teman perjalanan, siap berangkat</h3><p class="mt-1 max-w-sm text-[11px] leading-5 text-slate-500">Simpan data peserta agar pemesanan perjalanan berikutnya lebih mudah.</p></div></div>
                <button type="button" class="inline-flex min-h-9 items-center gap-2 rounded-lg bg-[#078cff] px-4 text-[11px] font-semibold text-white transition-colors hover:bg-[#0878db] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3E7BEF]" @click="openTraveler()"><Plus class="size-4" />Tambah wisatawan</button>
            </div>
            <div class="mt-4 rounded-2xl border border-[#e1eaf5] bg-white p-4 shadow-[0_4px_20px_rgba(23,75,120,0.04)]"><label class="flex h-10 items-center gap-2 rounded-xl border border-[#e1eaf5] px-3 focus-within:border-[#078cff] focus-within:ring-2 focus-within:ring-sky-100"><Search class="size-4 text-[#078cff]" /><input v-model="travelerSearch" type="search" placeholder="Cari nama wisatawan…" aria-label="Cari nama wisatawan" class="min-w-0 flex-1 bg-transparent text-xs outline-none" /></label></div>
            <section class="mt-4 overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]" aria-labelledby="travelers-heading">
                <div class="flex items-center justify-between gap-3 border-b border-slate-100 px-4 py-3"><h3 id="travelers-heading" class="flex items-center gap-2 text-xs font-semibold text-[#183660]"><Users class="size-4 text-[#3E7BEF]" />Wisatawan tersimpan</h3><span class="rounded-full bg-[#edf4ff] px-2.5 py-1 text-[10px] text-[#3E7BEF]" aria-live="polite">{{ travelers.length }} peserta</span></div>
                <div tabindex="0" role="region" aria-label="Daftar wisatawan, dapat digulir" class="max-h-[420px] space-y-3 overflow-y-auto overscroll-contain bg-[#f8fafc] p-3 sm:p-4 [scrollbar-width:thin] [scrollbar-color:#b9d5fa_transparent]">
                    <article v-for="person in visibleTravelers" :key="person.id" class="flex flex-wrap items-center gap-3 rounded-xl border border-[#e1eaf5] bg-white p-4 transition-colors hover:border-[#aacbff]"><span class="grid size-11 shrink-0 place-items-center rounded-xl bg-gradient-to-br from-[#edf4ff] to-[#d8eaff] text-base font-bold text-[#3E7BEF]">{{ person.name.charAt(0).toUpperCase() }}</span><div class="min-w-0 flex-1"><h4 class="break-words text-xs font-bold text-[#183660]">{{ person.name }}</h4><span class="mt-1.5 inline-block rounded-full bg-[#edf4ff] px-2 py-0.5 text-[9px] font-medium text-[#3E7BEF]">{{ person.relation }}</span></div><button type="button" :aria-label="`Edit data ${person.name}`" class="min-h-9 rounded-lg border border-blue-100 px-3 text-[10px] font-semibold text-[#078cff] transition-colors hover:bg-sky-50 focus-visible:outline-2 focus-visible:outline-[#3E7BEF]" @click="openTraveler(person)">Edit data</button></article>
                    <div v-if="!visibleTravelers.length" class="rounded-xl border border-[#e1eaf5] bg-white p-8 text-center"><Users class="mx-auto size-8 text-blue-200" /><p class="mt-3 text-xs font-semibold text-[#183660]">{{ travelerSearch ? 'Wisatawan tidak ditemukan' : 'Belum ada wisatawan tersimpan' }}</p><p class="mt-2 text-[11px] text-slate-500">{{ travelerSearch ? 'Coba cari dengan nama lainnya.' : 'Tambahkan peserta untuk perjalanan berikutnya.' }}</p></div>
                </div>
                <p class="border-t border-slate-100 px-4 py-3 text-[10px] text-slate-500" aria-live="polite">{{ visibleTravelers.length }} wisatawan ditampilkan</p>
            </section>
            <AccountExploreBanner />
        </template>

        <template v-else-if="section === 'Chat'">
            <div class="mt-5 grid overflow-hidden rounded-2xl border border-[#e1e8f3] bg-white lg:grid-cols-[210px_minmax(0,1fr)]">
                <div class="border-b border-slate-100 p-2 lg:border-b-0 lg:border-r"><button v-for="item in conversations" :key="item.id" class="flex w-full items-center gap-2 rounded-xl p-3 text-left" :class="selectedChat === item.id ? 'bg-sky-50' : 'hover:bg-slate-50'" @click="selectedChat = item.id; draft = ''"><MessageCircle class="size-5 shrink-0 text-[#078cff]" /><span><span class="block text-xs font-bold">{{ item.name }}</span><span class="mt-1 block text-[10px] text-slate-400">{{ item.subtitle }}</span></span></button></div>
                <div class="min-w-0"><h3 class="border-b border-slate-100 p-4 text-sm font-bold">{{ chat.name }}</h3><div class="flex h-80 flex-col gap-3 overflow-y-auto bg-[#f8fbff] p-4" aria-live="polite"><p v-for="(message, index) in chat.messages" :key="index" class="max-w-[85%] whitespace-pre-wrap break-words rounded-2xl px-4 py-3 text-xs leading-5" :class="message.own ? 'self-end bg-[#1045a5] text-white' : 'self-start border border-slate-100 bg-white text-slate-600'">{{ message.text }}</p></div><form class="flex gap-2 border-t border-slate-100 p-3" @submit.prevent="send"><input v-model="draft" maxlength="2000" placeholder="Tulis pesan contoh…" aria-label="Pesan chat" :class="control" /><button :class="primary" :disabled="!draft.trim()" aria-label="Tambahkan pesan ke pratinjau"><Send class="size-4" /></button></form></div>
            </div>
            <AccountExploreBanner />
        </template>

        <template v-else-if="section === 'Rating & Ulasan'">
            <template v-if="reviewView === 'orders'">
                <p v-if="reviewNotice" role="status" class="mt-4 flex items-center gap-2 rounded-xl border border-emerald-100 bg-emerald-50 px-3 py-2.5 text-[11px] text-emerald-700"><CheckCircle2 class="size-4 shrink-0" />{{ reviewNotice }}</p>
                <section class="mt-4 overflow-hidden rounded-2xl border border-[#d8e7f8] bg-white shadow-[0_8px_28px_rgba(23,75,120,0.06)]" aria-labelledby="review-orders-heading">
                    <div class="border-t-4 border-[#3E7BEF] border-b border-slate-100 px-4 py-3.5"><div class="flex flex-wrap items-center justify-between gap-3"><div class="flex items-center gap-2.5"><span class="grid size-9 place-items-center rounded-lg bg-[#edf4ff] text-[#3E7BEF]"><Star class="size-4" /></span><div><h3 id="review-orders-heading" class="text-xs font-bold text-[#183660]">Pesanan yang bisa diulas</h3><p class="mt-0.5 text-[10px] text-slate-500">Bagikan pengalamanmu setelah perjalanan selesai.</p></div></div><span class="rounded-full bg-[#edf4ff] px-2.5 py-1 text-[10px] font-semibold text-[#3E7BEF]">{{ completedOrders.filter(order => !order.reviewed).length }} menunggu</span></div></div>
                    <div ref="reviewScroll" tabindex="0" role="region" aria-label="Riwayat pesanan selesai, dapat digulir" class="max-h-[470px] space-y-3 overflow-y-auto overscroll-contain bg-[#f8fafc] p-3 sm:p-4 [scrollbar-width:thin] [scrollbar-color:#b9d5fa_transparent]">
                        <article v-for="order in visibleReviewOrders" :key="order.id" class="group overflow-hidden rounded-xl border border-[#e1eaf5] bg-white transition duration-200 hover:border-[#9fc8fb] hover:shadow-[0_6px_18px_rgba(31,96,170,0.07)]">
                            <div class="grid gap-3 p-3 sm:grid-cols-[112px_minmax(0,1fr)_144px_112px] sm:items-center sm:gap-3">
                                <div class="relative h-20 overflow-hidden rounded-lg sm:h-16"><img :src="`https://images.unsplash.com/photo-${order.image}?auto=format&fit=crop&w=360&q=85`" :alt="order.name" loading="lazy" class="size-full object-cover transition duration-500 group-hover:scale-105 motion-reduce:transform-none" /><span class="absolute left-2 top-2 rounded-md bg-white/95 px-1.5 py-0.5 text-[7px] font-semibold text-[#3E7BEF]">Open Trip</span></div>
                                <div class="min-w-0"><h4 class="truncate text-[10px] font-bold text-[#183660] sm:text-xs">{{ order.name }}</h4><div class="mt-1.5 space-y-1 text-[9px] text-slate-500"><p class="flex items-center gap-1"><MapPin class="size-3 shrink-0 text-[#5d93dd]" />{{ order.location }}</p><p class="flex items-center gap-1"><CalendarDays class="size-3 shrink-0 text-[#5d93dd]" />{{ order.date }}<span class="ml-2 hidden items-center gap-1 sm:inline-flex"><Users class="size-3" />2 Orang</span></p></div><span class="mt-2 inline-flex items-center gap-1 rounded-full bg-emerald-50 px-1.5 py-0.5 text-[8px] font-medium text-emerald-600"><CheckCircle2 class="size-2.5" />Perjalanan selesai</span></div>
                                <div class="flex items-center justify-between gap-2 rounded-lg border border-[#edf2f8] bg-[#f8fbff] px-3 py-2 sm:flex-col sm:items-start sm:justify-center"><p class="flex shrink-0 items-center gap-1 whitespace-nowrap text-[8px] font-medium text-[#5d7ca1]"><Star class="size-3 text-[#3E7BEF]" />Nilai pengalamanmu</p><div class="flex shrink-0 gap-1"><Star v-for="value in 5" :key="value" class="size-3" :class="order.reviewed ? 'fill-amber-400 text-amber-400' : 'text-[#8eb7ed]'" /></div></div>
                                <div class="flex items-center sm:justify-end"><span v-if="order.reviewed" class="inline-flex w-full items-center justify-center gap-1.5 rounded-lg bg-[#edf4ff] px-2 py-2 text-[9px] font-semibold text-[#3E7BEF]"><CheckCircle2 class="size-3.5" />Sudah diulas</span><button v-else type="button" class="inline-flex min-h-9 w-full items-center justify-center gap-1.5 rounded-lg bg-[#078cff] px-3 text-[9px] font-semibold text-white transition-colors hover:bg-[#0878db] focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-[#3E7BEF]" @click="openReview(order)">Beri ulasan <ChevronRight class="size-3" /></button></div>
                            </div>
                        </article>
                    </div>
                    <footer class="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 px-4 py-3"><p class="text-[10px] text-slate-500" aria-live="polite">Menampilkan {{ reviewStart + 1 }}–{{ Math.min(reviewStart + reviewPageSize, completedOrders.length) }} dari {{ completedOrders.length }} pesanan</p><nav aria-label="Halaman pesanan untuk ulasan" class="flex items-center gap-1"><button type="button" aria-label="Halaman sebelumnya" :disabled="reviewPage === 1" class="grid size-8 place-items-center rounded-full text-[#3E7BEF] hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-30" @click="goReviewPage(reviewPage - 1)"><ChevronLeft class="size-4" /></button><button v-for="number in reviewPageCount" :key="number" type="button" :aria-label="`Halaman ${number}`" :aria-current="reviewPage === number ? 'page' : undefined" class="grid size-8 place-items-center rounded-full text-xs font-semibold transition-colors" :class="reviewPage === number ? 'bg-[#3E7BEF] text-white shadow-[0_3px_9px_rgba(62,123,239,0.22)]' : 'text-slate-500 hover:bg-blue-50 hover:text-[#3E7BEF]'" @click="goReviewPage(number)">{{ number }}</button><button type="button" aria-label="Halaman berikutnya" :disabled="reviewPage === reviewPageCount" class="grid size-8 place-items-center rounded-full text-[#3E7BEF] hover:bg-blue-50 disabled:cursor-not-allowed disabled:opacity-30" @click="goReviewPage(reviewPage + 1)"><ChevronRight class="size-4" /></button></nav></footer>
                </section>
                <section v-if="reviews.length" class="mt-4 overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]"><div class="border-b border-slate-100 px-4 py-3 text-xs font-semibold text-[#183660]">Ulasan saya</div><div class="space-y-3 bg-[#f8fafc] p-3 sm:p-4"><article v-for="review in reviews" :key="review.id" class="rounded-xl border border-[#e1eaf5] bg-white p-4"><div class="flex flex-wrap items-center justify-between gap-2"><h4 class="text-xs font-bold text-[#183660]">{{ review.orderName }}</h4><span class="inline-flex items-center gap-1 text-[10px] font-semibold text-amber-600"><Star class="size-3.5 fill-amber-400 text-amber-400" />{{ review.rating }} / 5</span></div><p class="mt-2 whitespace-pre-wrap break-words text-[11px] leading-5 text-slate-600">{{ review.text }}</p><span class="mt-2 block text-[9px] text-slate-400">Pratinjau · Belum dipublikasikan</span></article></div></section>
            </template>
            <form v-else class="mt-4 overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]" @submit.prevent="saveReview">
                <div class="flex items-center gap-3 border-b border-slate-100 px-4 py-3"><button type="button" class="grid size-8 place-items-center rounded-lg text-[#3E7BEF] hover:bg-[#edf4ff]" aria-label="Kembali ke pesanan" @click="reviewView = 'orders'"><ArrowLeft class="size-4" /></button><div><h3 class="text-xs font-semibold text-[#183660]">Beri ulasan</h3><p class="mt-0.5 text-[10px] text-slate-500">Bagikan pengalaman perjalananmu.</p></div></div>
                <div class="space-y-5 p-4 sm:p-5">
                    <div class="flex gap-3 rounded-xl border border-[#e1eaf5] bg-[#f8fafc] p-3"><img :src="`https://images.unsplash.com/photo-${reviewOrder.image}?auto=format&fit=crop&w=240&q=85`" :alt="reviewOrder.name" class="size-14 rounded-lg object-cover" /><div><h4 class="text-xs font-bold text-[#183660]">{{ reviewOrder.name }}</h4><p class="mt-1 text-[10px] text-slate-500">{{ reviewOrder.location }}</p><p class="mt-1 text-[9px] text-slate-400">{{ reviewOrder.date }}</p></div></div>
                    <fieldset><legend class="text-xs font-semibold text-[#183660]">Bagaimana pengalamanmu?</legend><div class="mt-3 flex gap-2"><button v-for="value in 5" :key="value" type="button" class="grid size-10 place-items-center rounded-xl border transition-colors focus-visible:outline-2 focus-visible:outline-[#3E7BEF]" :class="value <= rating ? 'border-amber-200 bg-amber-50 text-amber-500' : 'border-[#e1eaf5] bg-white text-slate-300 hover:bg-[#f8fafc]'" :aria-label="`Rating ${value} dari 5`" :aria-pressed="rating === value" @click="rating = value"><Star class="size-5" :class="value <= rating ? 'fill-current' : ''" /></button></div></fieldset>
                    <div><div class="mb-2 flex items-center justify-between gap-3"><label for="review-editor" class="text-xs font-semibold text-[#183660]">Ceritakan pengalamanmu</label><span class="text-[9px] text-slate-400">Minimal 10 karakter</span></div><div class="overflow-hidden rounded-xl border border-[#e1eaf5] bg-white focus-within:border-[#9fc8fb] focus-within:ring-2 focus-within:ring-blue-50"><div class="flex items-center gap-1 border-b border-slate-100 bg-[#fbfdff] px-2 py-1.5"><button type="button" class="grid size-7 place-items-center rounded-md text-[#597494] hover:bg-[#edf4ff] hover:text-[#3E7BEF]" aria-label="Tebal" title="Tebal" @click="formatReview('bold')"><Bold class="size-3.5" /></button><button type="button" class="grid size-7 place-items-center rounded-md text-[#597494] hover:bg-[#edf4ff] hover:text-[#3E7BEF]" aria-label="Miring" title="Miring" @click="formatReview('italic')"><Italic class="size-3.5" /></button><button type="button" class="grid size-7 place-items-center rounded-md text-[#597494] hover:bg-[#edf4ff] hover:text-[#3E7BEF]" aria-label="Daftar poin" title="Daftar poin" @click="formatReview('insertUnorderedList')"><List class="size-3.5" /></button><span class="mx-1 h-5 w-px bg-slate-200"></span><input ref="reviewImageInput" type="file" accept="image/jpeg,image/png,image/webp" multiple class="hidden" @change="addReviewImages" /><button type="button" :disabled="reviewImages.length === 5" class="inline-flex min-h-7 items-center gap-1 rounded-md px-2 text-[9px] font-semibold text-[#3E7BEF] hover:bg-[#edf4ff] disabled:cursor-not-allowed disabled:opacity-40" @click="reviewImageInput.click()"><ImagePlus class="size-3.5" />Tambah foto</button></div><div id="review-editor" ref="reviewEditor" contenteditable="true" role="textbox" aria-multiline="true" aria-label="Isi ulasan" data-placeholder="Apa yang paling berkesan dari perjalanan ini?" class="min-h-32 px-3 py-3 text-xs leading-5 text-slate-700 outline-none empty:before:pointer-events-none empty:before:content-[attr(data-placeholder)] empty:before:text-slate-400" @input="updateReviewText" @blur="updateReviewText"></div></div><div v-if="reviewImages.length" class="mt-3 flex flex-wrap gap-2"><div v-for="image in reviewImages" :key="image.id" class="group relative size-20 overflow-hidden rounded-lg border border-[#e1eaf5]"><img :src="image.url" :alt="image.name" class="size-full object-cover" /><button type="button" :aria-label="`Hapus foto ${image.name}`" class="absolute right-1 top-1 grid size-6 place-items-center rounded-full bg-slate-900/65 text-white opacity-0 transition-opacity group-hover:opacity-100 focus-visible:opacity-100" @click="removeReviewImage(image)"><Trash2 class="size-3" /></button></div></div><p class="mt-2 text-[9px] leading-4 text-slate-400">Tambahkan maksimal 5 foto JPG, PNG, atau WebP. Maksimal 2 MB per foto.</p></div>
                    <p v-if="reviewError" role="alert" class="text-[11px] text-rose-600">{{ reviewError }}</p>
                </div>
                <div class="flex justify-end gap-2 border-t border-slate-100 bg-[#fbfcfe] px-4 py-3"><button type="button" class="min-h-9 rounded-lg border border-[#e1eaf5] bg-white px-4 text-[10px] font-semibold text-slate-600 hover:bg-slate-50" @click="reviewView = 'orders'">Batal</button><button class="min-h-9 rounded-lg bg-[#078cff] px-4 text-[10px] font-semibold text-white hover:bg-[#0878db]">Kirim ulasan</button></div>
            </form>
            <AccountExploreBanner />
        </template>

        <template v-else-if="section === 'Pesan Bantuan'">
            <section class="mt-4 rounded-2xl border border-[#c7e5f5] bg-gradient-to-r from-[#edf5ff] via-white to-[#e7f8f7] p-4 sm:p-5"><div class="flex flex-wrap items-center justify-between gap-4"><div class="flex items-start gap-3"><span class="grid size-11 shrink-0 place-items-center rounded-xl bg-[#3E7BEF] text-white shadow-[0_4px_12px_rgba(62,123,239,0.2)]"><MessageCircle class="size-5" /></span><div><h3 class="text-sm font-bold text-[#183660]">Butuh bantuan perjalanan?</h3><p class="mt-1 max-w-md text-[11px] leading-5 text-slate-500">Pilih topik, tuliskan kendala, dan simpan pesanmu untuk ditinjau.</p></div></div><span class="rounded-full border border-blue-100 bg-white/85 px-2.5 py-1 text-[10px] font-semibold text-[#3E7BEF]">Pusat bantuan</span></div></section>
            <div class="mt-4 grid gap-4 xl:grid-cols-[minmax(0,1fr)_220px]">
                <form class="overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]" @submit.prevent="saveTicket"><div class="border-b border-slate-100 px-4 py-3"><h3 class="text-xs font-semibold text-[#183660]">Kirim pesan bantuan</h3><p class="mt-1 text-[10px] text-slate-500">Jangan sertakan kata sandi atau data pembayaran sensitif.</p></div><div class="space-y-4 p-4 sm:p-5"><fieldset><legend class="text-xs font-semibold text-[#183660]">Pilih topik</legend><div class="mt-2 flex flex-wrap gap-2"><button v-for="item in ['Pemesanan', 'Pembayaran', 'Voucher & Points', 'Akun', 'Lainnya']" :key="item" type="button" class="min-h-8 rounded-full border px-3 text-[10px] font-semibold transition-colors focus-visible:outline-2 focus-visible:outline-[#3E7BEF]" :class="category === item ? 'border-[#3E7BEF] bg-[#3E7BEF] text-white shadow-sm' : 'border-[#e1eaf5] bg-white text-slate-500 hover:bg-[#edf4ff] hover:text-[#3E7BEF]'" @click="category = item">{{ item }}</button></div></fieldset><label class="flex flex-col gap-2 text-xs font-semibold text-[#183660]">Judul pesan<input v-model="subject" required maxlength="120" placeholder="Ringkasan kendalamu" class="h-10 rounded-xl border border-[#e1eaf5] px-3 text-xs font-normal outline-[#078cff] focus:border-[#9fc8fb]" /></label><label class="flex flex-col gap-2 text-xs font-semibold text-[#183660]">Detail kendala<textarea v-model="helpText" required minlength="10" maxlength="3000" rows="5" placeholder="Jelaskan kendala agar kami dapat memahami situasinya." class="resize-y rounded-xl border border-[#e1eaf5] px-3 py-3 text-xs font-normal leading-5 outline-[#078cff] focus:border-[#9fc8fb]"></textarea><span class="text-[9px] font-normal text-slate-400">{{ helpText.length }} / 3000 karakter</span></label></div><div class="flex justify-end gap-2 border-t border-slate-100 bg-[#fbfcfe] px-4 py-3"><button type="button" class="min-h-9 rounded-lg border border-[#e1eaf5] bg-white px-4 text-[10px] font-semibold text-slate-600 hover:bg-slate-50" @click="subject = ''; helpText = ''">Bersihkan</button><button class="min-h-9 rounded-lg bg-[#078cff] px-4 text-[10px] font-semibold text-white hover:bg-[#0878db]">Kirim pesan</button></div></form>
                <aside class="relative isolate flex min-h-full flex-col overflow-hidden rounded-2xl border border-[#c7e5f5] bg-gradient-to-b from-[#edf5ff] via-white to-[#e8f8f7] shadow-[0_4px_20px_rgba(23,75,120,0.04)]"><div aria-hidden="true" class="absolute -right-12 -top-10 -z-10 size-40 rounded-full border-[24px] border-white/70"></div><div class="border-b border-white/80 px-4 py-4"><div class="flex items-center gap-2"><span class="grid size-8 place-items-center rounded-lg bg-white text-[#3E7BEF] shadow-sm"><MessageCircle class="size-4" /></span><div><h3 class="text-xs font-semibold text-[#183660]">Sebelum mengirim</h3><p class="mt-0.5 text-[9px] text-slate-500">Buat pesanmu lebih mudah dipahami.</p></div></div></div><div class="relative space-y-4 p-4"><div class="absolute bottom-8 left-[29px] top-8 w-px bg-[#cfe2fb]"></div><div class="relative flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full border border-blue-100 bg-white text-[11px] font-semibold text-[#3E7BEF]">1</span><div><p class="text-[10px] font-semibold text-[#183660]">Pilih topik yang tepat</p><p class="mt-1 text-[10px] leading-5 text-slate-500">Agar pesanmu masuk ke kategori bantuan yang sesuai.</p></div></div><div class="relative flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full border border-blue-100 bg-white text-[11px] font-semibold text-[#3E7BEF]">2</span><div><p class="text-[10px] font-semibold text-[#183660]">Tulis detail pesanan</p><p class="mt-1 text-[10px] leading-5 text-slate-500">Sertakan kode pesanan atau transaksi jika berkaitan.</p></div></div><div class="relative flex gap-3"><span class="grid size-8 shrink-0 place-items-center rounded-full border border-blue-100 bg-white text-[11px] font-semibold text-[#3E7BEF]">3</span><div><p class="text-[10px] font-semibold text-[#183660]">Jaga data pribadimu</p><p class="mt-1 text-[10px] leading-5 text-slate-500">Jangan kirim kata sandi, PIN, atau kode OTP.</p></div></div></div><div class="mt-auto border-t border-white/80 bg-white/60 p-4"><div class="rounded-xl border border-white bg-white/80 p-3"><p class="text-[10px] font-semibold text-[#183660]">Perlu bantuan cepat?</p><p class="mt-1 text-[9px] leading-4 text-slate-500">Cek riwayat transaksi atau pesananmu untuk menemukan informasi yang diperlukan.</p></div></div></aside>
            </div>
            <section v-if="tickets.length" class="mt-4 overflow-hidden rounded-2xl border border-[#e1eaf5] bg-white shadow-[0_4px_20px_rgba(23,75,120,0.04)]"><div class="flex items-center justify-between border-b border-slate-100 px-4 py-3"><h3 class="text-xs font-semibold text-[#183660]">Pesan bantuan tersimpan</h3><span class="rounded-full bg-[#edf4ff] px-2.5 py-1 text-[10px] text-[#3E7BEF]">{{ tickets.length }} pesan</span></div><div class="space-y-3 bg-[#f8fafc] p-3 sm:p-4"><article v-for="ticket in tickets" :key="ticket.id" class="rounded-xl border border-[#e1eaf5] bg-white p-4"><div class="flex flex-wrap items-center justify-between gap-2"><span class="rounded-full bg-[#edf4ff] px-2 py-0.5 text-[9px] font-semibold text-[#3E7BEF]">{{ ticket.category }}</span><span class="text-[9px] text-slate-400">{{ ticket.date }}</span></div><h4 class="mt-2 text-xs font-bold text-[#183660]">{{ ticket.subject }}</h4><p class="mt-2 whitespace-pre-wrap break-words text-[11px] leading-5 text-slate-600">{{ ticket.text }}</p><span class="mt-3 inline-flex rounded-full bg-amber-50 px-2 py-1 text-[9px] font-medium text-amber-700">Draf lokal</span></article></div></section>
            <AccountExploreBanner />
        </template>
        <p class="mt-4 text-[10px] leading-5 text-slate-400">Pratinjau lokal · Data contoh dan perubahan tidak disimpan ke server. Chat, ulasan, dan bantuan tidak dikirim kepada pihak lain.</p>
        <dialog ref="dialog" class="fixed inset-0 m-auto w-[calc(100%-2rem)] max-w-md rounded-2xl bg-white p-6 text-slate-700 backdrop:bg-slate-900/50" aria-labelledby="traveler-dialog"><form class="space-y-4" @submit.prevent="saveTraveler"><div class="flex justify-between"><h2 id="traveler-dialog" class="font-bold">{{ editing ? 'Edit' : 'Tambah' }} wisatawan</h2><button type="button" aria-label="Tutup" @click="dialog.close()"><X class="size-5" /></button></div><label class="flex flex-col gap-2 text-xs">Nama lengkap<input v-model="travelerName" autofocus required maxlength="100" :class="control" /></label><label class="flex flex-col gap-2 text-xs">Hubungan<select v-model="relation" :class="control"><option>Diri sendiri</option><option>Keluarga</option><option>Teman</option><option>Lainnya</option></select></label><button :disabled="!travelerName.trim()" class="min-h-10 w-full rounded-xl bg-[#078cff] px-4 text-xs font-semibold text-white hover:bg-[#0878db] disabled:cursor-not-allowed disabled:opacity-40">Simpan wisatawan</button></form></dialog>
    </section>
</template>
