<script setup>
import { computed, ref } from 'vue';
import { Search, ChevronRight } from 'lucide-vue-next';
import PanoramaMark from '../Shared/PanoramaMark.vue';
import PanoramaViewer from '../Shared/PanoramaViewer.vue';
const props = defineProps({ tours: { type: Array, default: () => [] } });
const query = ref(''), chosen = ref(null);
const active = computed(() => props.tours.find(tour => tour.id === chosen.value) || props.tours[0]);
const filtered = computed(() => props.tours.filter(tour => tour.title.toLocaleLowerCase('id-ID').includes(query.value.toLocaleLowerCase('id-ID'))));
</script>
<template><section class="mx-auto mt-20 grid max-w-[1180px] gap-2.5 text-[#172c70] sm:mt-24 lg:grid-cols-[704fr_462fr]" aria-labelledby="destination-gallery-heading"><div class="min-w-0 rounded-2xl bg-white/95 p-5 sm:p-6"><div class="mb-5 flex items-start gap-3"><PanoramaMark class="size-11 shrink-0 text-[#078cff]" /><div><h2 id="destination-gallery-heading" class="text-lg font-bold text-[#172c70]">Jelajahi Destinasi dalam 360°</h2><p class="mt-1 text-xs leading-5 text-[#788caf]">Rasakan pengalaman virtual sebelum kamu berangkat. Pilih panorama untuk melihat suasana destinasi.</p></div></div><PanoramaViewer v-if="active" :key="active.id" :tour="active" /><p v-else class="rounded-xl bg-sky-50 p-12 text-center text-sm">Panorama belum diterbitkan.</p><div class="mt-3 flex gap-2.5 overflow-x-auto pb-2"><button v-for="tour in tours" :key="tour.id" type="button" class="relative h-24 w-36 shrink-0 overflow-hidden rounded-xl border-2" :class="active?.id === tour.id ? 'border-blue-500' : 'border-transparent'" :aria-pressed="active?.id === tour.id" @click="chosen = tour.id"><img :src="tour.image_url" alt="" loading="lazy" class="size-full object-cover" /><span class="absolute inset-x-0 bottom-0 bg-slate-950/75 p-2 text-left text-[10px] text-white">{{ tour.title }}</span></button></div></div><div class="flex max-h-[690px] min-h-80 flex-col rounded-2xl bg-white/95 p-5 sm:p-6"><label class="mb-4 flex items-center gap-3 rounded-xl border border-[#e5edf8] bg-[#f8fbff] px-3.5 py-3"><Search class="size-5 text-[#078cff]" /><input v-model="query" type="search" placeholder="Cari destinasi..." aria-label="Cari panorama destinasi" class="w-full bg-transparent text-xs outline-none" /></label><div class="grid min-h-0 gap-2.5 overflow-y-auto"><button v-for="tour in filtered" :key="tour.id" type="button" class="flex items-center gap-3 rounded-xl border p-2 text-left" :class="active?.id === tour.id ? 'border-[#8bc5ff] bg-[#edf5ff]' : 'border-[#e5edf8] bg-white'" @click="chosen = tour.id"><img :src="tour.image_url" alt="" loading="lazy" class="h-16 w-24 rounded-lg object-cover" /><span class="flex-1"><strong class="text-xs">{{ tour.title }}</strong><span class="mt-1 block text-[10px] text-slate-500">Panorama 360°</span></span><ChevronRight class="size-4 text-blue-500" /></button><p v-if="!filtered.length" class="p-6 text-center text-xs text-slate-500"></p></div></div></section></template>
