export const articles = [
    {
        id: 'bali',
        category: 'Inspirasi Destinasi',
        title: 'Menikmati sisi tenang Bali, jauh dari keramaian',
        image: '1537996194471-e657df975ab4',
        excerpt: 'Dari suasana pura hingga pesisir yang menenangkan, temukan ide untuk perjalanan yang lebih santai dan otentik di Pulau Dewata.',
        body: 'Sisakan waktu untuk menikmati satu daerah tanpa terburu-buru berpindah tempat. Berjalan di sekitar penginapan, mencoba warung setempat, dan berbincang dengan pemandu lokal bisa menjadi bagian paling berkesan dari perjalanan. Saat mengunjungi pura, ikuti petunjuk berpakaian dan hormati area yang khusus digunakan untuk ibadah.',
        date: '12 Sep 2026',
        readTime: '5 menit baca',
        views: '2.4k dibaca',
        location: 'Bedugul & Sidemen, Bali',
        heroCaption: 'Pura Ulun Danu Beratan di kala pagi yang tenang dengan kabut pegunungan Bedugul',
        author: {
            name: 'Wayan Artha Kusuma',
            role: 'Local Guide & Storyteller Bali',
            avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
            bio: 'Lahir dan besar di Karangasem. Aktif mendampingi pelancong yang ingin merasakan kehidupan desa dan keindahan alam Bali tanpa terburu-buru.',
            badge: 'Pemandu Terverifikasi',
            storiesCount: 18,
        },
        quickFacts: {
            bestTime: 'Mei – Oktober (Musim Kering)',
            budget: 'Rp 350.000 – 600.000 / hari',
            duration: '3 – 5 Hari Rekomendasi',
            access: 'Mobil sewa / Sepeda motor lokal',
            language: 'Bahasa Indonesia & Bali',
        },
        gallery: [
            'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=1200&q=88',
        ],
        tags: ['Wisata Tenang', 'Budaya Bali', 'Inspirasi Perjalanan', 'Ekowisata', 'Kuliner Lokal'],
        reactions: {
            helpful: 142,
            inspiring: 98,
            wantToGo: 215,
        },
        sections: [
            {
                id: 'ritme-pelan',
                heading: 'Menemukan Ritme yang Lebih Pelan di Pedalaman',
                content: [
                    'Sering kali kita terbiasa dengan jadwal liburan yang padat: berpindah dari satu pantai populer ke kafe hits dalam hitungan jam. Namun di Bali bagian timur dan dataran tinggi Bedugul, waktu seolah berjalan lebih bersahabat. Udara sejuk pegunungan dan gemericik air irigasi subak menghadirkan ketenangan yang jarang dijumpai di kawasan pesisir selatan.',
                    'Memilih tinggal beberapa hari di desa seperti Sidemen atau Munduk memberikan pengalaman berbeda. Pagi hari diawali dengan aroma dupa canang sari segar dan sapaan ramah warga yang berangkat ke ladang. Tidak ada klakson jalanan, hanya suara burung dan hamparan perbukitan hijau yang memanjakan mata.',
                ],
                quote: {
                    text: 'Perjalanan terbaik bukanlah tentang berapa banyak tempat yang kamu foto, melainkan seberapa dalam kamu terhubung dengan tanah dan orang-orang yang kamu temui.',
                    author: 'I Made Sujana, Tetua Desa Sidemen',
                },
                image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1000&q=85',
                imageCaption: 'Hamparan terasering sawah berundak dengan latar perbukitan di kawasan Sidemen',
            },
            {
                id: 'etika-budaya',
                heading: 'Menghormati Tradisi dan Tata Krama di Area Pura',
                content: [
                    'Kunjungan ke situs budaya dan pura suci menuntut kesadaran kita sebagai tamu. Mengenakan kain kamen dan selendang (senteng) bukan sekadar formalitas, melainkan wujud penghormatan tulus terhadap kesucian tempat peribadatan masyarakat Hindu Bali.',
                    'Hindari melintas di depan orang yang sedang khusyuk sembahyang atau berdiri lebih tinggi dari pemangku yang memimpin upacara. Tanyakan selalu kepada pemandu lokal mengenai area mana saja yang terbuka untuk wisatawan dan area mana yang khusus untuk ritual.',
                ],
                proTip: {
                    title: 'Tips Praktis TapakLokal',
                    items: [
                        'Siapkan kain kamen sendiri untuk kenyamanan ekstra dan mengurangi limbah plastik penyewaan sekali pakai.',
                        'Kunjungi pura danau di pagi hari sebelum pukul 08.00 WIB untuk mendapatkan kabut mistis dan ketenangan maksimal.',
                        'Gunakan alas kaki yang mudah dilepas karena beberapa pelataran mengharuskan berjalan tanpa alas.',
                    ],
                },
            },
            {
                id: 'kuliner-otentik',
                heading: 'Mencicipi Kuliner Rumahan yang Jujur',
                content: [
                    'Jauh dari restoran megah, kehangatan rasa Bali paling terasa di warung-warung sederhana milik keluarga. Nasi campur Bali dengan olahan base genep tradisional, lawar sayur nangka muda, dan sambal matah dengan minyak kelapa asli menghadirkan kelezatan yang tulus.',
                    'Duduk di bale bambu sembari berbincang dengan pemilik warung tentang asal rempah-rempah yang dipanen dari kebun belakang seringkali melahirkan cerita yang jauh lebih berharga daripada panduan buku manapun.',
                ],
                spots: [
                    {
                        name: 'Pura Ulun Danu Beratan',
                        location: 'Candikuning, Baturiti, Tabanan',
                        hours: '07.00 – 19.00 WITA',
                        ticket: 'Rp 40.000 / orang',
                        note: 'Paling bagus difoto saat kabut pagi menyentuh permukaan danau.',
                    },
                    {
                        name: 'Teras Sawah Sidemen',
                        location: 'Karangasem, Bali Timur',
                        hours: 'Buka 24 Jam',
                        ticket: 'Gratis (Donasi Kebersihan Desa)',
                        note: 'Jalur trekking santai ramah keluarga dengan pemandangan Gunung Agung.',
                    },
                ],
            },
        ],
        relatedTrip: {
            title: 'Private Trip Jelajah Bali Timur & Danau Bedugul',
            slug: 'bali-timur-bedugul',
            type: 'private-trip',
            duration: '3H2M',
            price: 'Rp 1.850.000',
            originalPrice: 'Rp 2.200.000',
            image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=800&q=84',
            rating: 4.9,
            reviewsCount: 312,
            badge: 'Favorit Traveler',
        },
        initialComments: [
            {
                id: 1,
                name: 'Anindya Putri',
                avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&q=80',
                role: 'Solo Traveler',
                date: '2 hari yang lalu',
                rating: 5,
                content: 'Artikel yang sangat menyejukkan! Minggu lalu saya mencoba menginap di Sidemen sesuai rekomendasi artikel ini dan suasananya benar-benar menyembuhkan penat kerjaan di Jakarta.',
                likes: 19,
            },
            {
                id: 2,
                name: 'Budi Darmawan',
                avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=120&q=80',
                role: 'Traveler Keluarga',
                date: '4 hari yang lalu',
                rating: 5,
                content: 'Sangat setuju soal etika di pura. Pemandu lokal dari TapakLokal kemarin sangat detail menjelaskan makna canang dan tata krama berpakaian.',
                likes: 12,
            },
        ],
    },
    {
        id: 'islands',
        category: 'Tips Perjalanan',
        title: 'Pertama kali island hopping? Mulai dari sini',
        image: '1516690561799-46d8f74f9abf',
        excerpt: 'Persiapan sederhana agar perjalanan antarpulau terasa lebih nyaman, aman, dan berkesan bersama operator lokal.',
        body: 'Pilih rute yang memberi cukup waktu untuk beristirahat. Konfirmasikan titik temu, fasilitas kapal, serta perlengkapan keselamatan kepada operator sebelum berangkat. Siapkan tas tahan air untuk barang penting, botol minum, dan pakaian ganti. Jadwal perjalanan laut dapat berubah mengikuti cuaca; beri ruang fleksibel dalam rencanamu.',
        date: '10 Sep 2026',
        readTime: '4 menit baca',
        views: '1.9k dibaca',
        location: 'Kepulauan Seribu & Labuan Bajo',
        heroCaption: 'Perjalanan laut melintasi pulau karang dengan air toska jernih di perairan tropis',
        author: {
            name: 'Rian Hidayat',
            role: 'Trip Leader & Marine Enthusiast',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
            bio: 'Berpengalaman memandu lebih dari 200 trip kepulauan di Indonesia. Senang membagikan tips keselamatan laut dan dokumentasi pulau terluar.',
            badge: 'Kapten Terverifikasi',
            storiesCount: 24,
        },
        quickFacts: {
            bestTime: 'April – Oktober (Ombak Tenang)',
            budget: 'Rp 450.000 – 1.200.000 / paket',
            duration: '2H1M – 3H2M',
            access: 'Speedboat / Kapal Kayu Tradisional',
            language: 'Bahasa Indonesia',
        },
        gallery: [
            'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=1200&q=88',
        ],
        tags: ['Island Hopping', 'Laut Indonesia', 'Open Trip', 'Tips Bahari', 'Snorkeling'],
        reactions: {
            helpful: 189,
            inspiring: 110,
            wantToGo: 320,
        },
        sections: [
            {
                id: 'persiapan-tas',
                heading: 'Dry Bag dan Perlengkapan Wajib yang Tidak Boleh Tertinggal',
                content: [
                    'Air laut dan cipratan ombak adalah kawan setia saat berlayar antarpulau. Membawa dry bag berkapasitas 10–20 liter adalah investasi terbaik untuk menjaga smartphone, dompet, dan kamera tetap aman sepanjang perjalanan.',
                    'Gunakan pakaian berbahan cepat kering (quick-dry) dan selalu siapkan jaket angin ringan. Angin laut di sore hari bisa terasa menusuk setelah seharian terpapar sinar matahari dan berenang di laut lepas.',
                ],
                quote: {
                    text: 'Laut selalu menghargai mereka yang datang dengan persiapan matang dan kerendahan hati.',
                    author: 'Kapten Rustam, Pelaut Pulau Pramuka',
                },
                image: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=85',
                imageCaption: 'Persiapan menaiki kapal tradisional bersama pemandu lokal di dermaga',
            },
            {
                id: 'keselamatan-kapal',
                heading: 'Etika dan Keselamatan di Atas Kapal',
                content: [
                    'Sebelum kapal bertolak dari dermaga, pastikan kamu mengetahui lokasi pelampung (life jacket) dan kenakan saat melewati perairan berarus. Dengarkan aba-aba kapten dan anak buah kapal yang paling memahami karasteristik pasang surut air laut.',
                    'Jangan membuang sampah apapun ke laut, termasuk puntung rokok atau sisa makanan kemasan. Simpan di kantong sampah pribadi hingga kapal kembali bersandar di pelabuhan utama.',
                ],
                proTip: {
                    title: 'Checklist Sebelum Naik Kapal',
                    items: [
                        'Minum obat antimabuk 30 menit sebelum kapal lepas tali jika rentan mabuk laut.',
                        'Simpan dokumen penting dalam kantong ziplock ganda di dalam tas tahan air.',
                        'Bawa botol minum isi ulang untuk mengurangi sampah botol plastik sekali pakai.',
                    ],
                },
            },
        ],
        relatedTrip: {
            title: 'Open Trip Tur Pulau Pramuka & Semak Daun',
            slug: 'pulau-pramuka',
            type: 'open-trip',
            duration: '2H1M',
            price: 'Rp 450.000',
            originalPrice: 'Rp 550.000',
            image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=800&q=84',
            rating: 4.9,
            reviewsCount: 428,
            badge: 'Best Seller',
        },
        initialComments: [
            {
                id: 1,
                name: 'Dimas Satrio',
                avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&q=80',
                role: 'Penjelajah Bahari',
                date: '1 hari yang lalu',
                rating: 5,
                content: 'Tips dry bag beneran penyelamat! Waktu trip ke Semak Daun kemarin sempat ombak kencang tapi kamera dan HP aman total.',
                likes: 8,
            },
        ],
    },
    {
        id: 'local',
        category: 'Cerita Lokal',
        title: 'Liburan lebih berarti dengan mendukung usaha lokal',
        image: '1518548419970-58e3b4079ab2',
        excerpt: 'Pilihan kecil dalam perjalananmu bisa memberi dampak nyata bagi kesejahteraan masyarakat di destinasi.',
        body: 'Cobalah makan di warung milik warga, menggunakan jasa pemandu setempat, dan membeli kerajinan langsung dari pembuatnya. Tanyakan cerita di balik produk yang kamu temui. Selalu minta izin sebelum memotret orang dan hormati kebiasaan komunitas yang kamu kunjungi.',
        date: '7 Sep 2026',
        readTime: '4 menit baca',
        views: '1.6k dibaca',
        location: 'Flores, NTT & Desa Sade, Lombok',
        heroCaption: 'Ibu penenun kain tradisional Flores dengan motif khas warisan leluhur',
        author: {
            name: 'Siti Nurhaliza',
            role: 'Community Development Specialist',
            avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80',
            bio: 'Fokus mendampingi UMKM desa wisata dan pengrajin lokal agar dapat terhubung dengan traveler secara berdaya dan adil.',
            badge: 'Pegiat Komunitas',
            storiesCount: 15,
        },
        quickFacts: {
            bestTime: 'Sepanjang Tahun',
            budget: 'Rp 200.000 – 500.000 untuk belanja UMKM',
            duration: 'Fleksibel',
            access: 'Jelajah jalan kaki di desa wisata',
            language: 'Bahasa Daerah & Indonesia',
        },
        gallery: [
            'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1200&q=88',
        ],
        tags: ['UMKM Lokal', 'Kain Tenun', 'Ekonomi Desa', 'Wisata Berkelanjutan', 'Cerita Warga'],
        reactions: {
            helpful: 210,
            inspiring: 180,
            wantToGo: 165,
        },
        sections: [
            {
                id: 'kekuatan-pilihan',
                heading: 'Uang Belanja yang Berputar Langsung di Meja Warga',
                content: [
                    'Saat kita memilih bersantap di warung makan warga lokal atau membeli buah tangan langsung dari sang perajin, rupiah yang kita keluarkan langsung berdampak pada pendidikan anak-anak mereka dan keberlanjutan tradisi leluhur.',
                    'Kain tenun ikat misalnya, membutuhkan waktu pengerjaan berbulan-bulan dengan pewarna alami dari akar mengkudu dan daun nila. Membeli dengan harga pantas tanpa menawar secara berlebihan adalah bentuk apresiasi tertinggi terhadap karya seni mereka.',
                ],
                quote: {
                    text: 'Setiap lembar benang yang ditenun adalah doa dan ingatan tentang tanah kelahiran kami.',
                    author: 'Mama Maria, Penenun Desa Sikka Flores',
                },
                image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=1000&q=85',
                imageCaption: 'Proses pemintalan benang dan pewarnaan alami di pekarangan rumah adat',
            },
        ],
        relatedTrip: {
            title: 'Private Trip Budaya & Alam Labuan Bajo - Flores',
            slug: 'labuan-bajo',
            type: 'private-trip',
            duration: '3H2M',
            price: 'Rp 2.850.000',
            originalPrice: 'Rp 3.250.000',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=84',
            rating: 4.9,
            reviewsCount: 189,
            badge: 'Pengalaman Autentik',
        },
        initialComments: [
            {
                id: 1,
                name: 'Kartika Sari',
                avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=120&q=80',
                role: 'Travel Blogger',
                date: '3 hari yang lalu',
                rating: 5,
                content: 'Sangat menyentuh. Penting bagi kita traveler modern untuk tidak sekadar selfie, tapi juga paham sejarah di balik tiap kerajinan yang dibeli.',
                likes: 15,
            },
        ],
    },
    {
        id: 'packing',
        category: 'Panduan Liburan',
        title: 'Packing ringan untuk liburan singkat ke pantai',
        image: '1501179691627-eeaa65ea017c',
        excerpt: 'Bawa yang kamu perlukan dan sisakan ruang untuk cerita baru tanpa repot membawa koper besar.',
        body: 'Mulai dari kebutuhan utama: dokumen perjalanan, obat pribadi, pakaian nyaman, dan perlengkapan mandi seperlunya. Gunakan tas kecil untuk kegiatan harian dan simpan barang elektronik dalam pelindung tahan air. Periksa fasilitas penginapan sebelum membawa handuk atau perlengkapan tambahan.',
        date: '4 Sep 2026',
        readTime: '3 menit baca',
        views: '2.1k dibaca',
        location: 'Tips & Hacks Traveler',
        heroCaption: 'Penyusunan barang bawaan ransel pantai yang efisien dan fungsional',
        author: {
            name: 'Reza Pratama',
            role: 'Ultralight Traveler & Outdoor Gear Reviewer',
            avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=200&q=80',
            bio: 'Penggemar ransel 25 liter untuk perjalanan seminggu. Mengajarkan seni traveling ringkas tanpa mengorbankan kenyamanan.',
            badge: 'Spesialis Packing',
            storiesCount: 12,
        },
        quickFacts: {
            bestTime: 'Kapan Saja',
            budget: 'Hemat & Praktis',
            duration: '2 – 4 Hari Trip',
            access: 'Cabin Backpack 30L',
            language: 'Bahasa Indonesia',
        },
        gallery: [
            'https://images.unsplash.com/photo-1501179691627-eeaa65ea017c?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88',
        ],
        tags: ['Tips Packing', 'Liburan Pantai', 'Minimalis', 'Gear Guide', 'Short Trip'],
        reactions: {
            helpful: 245,
            inspiring: 87,
            wantToGo: 130,
        },
        sections: [
            {
                id: 'aturan-tiga-pakaian',
                heading: 'Metode 3 Set Pakaian: Cukup dan Ringkas',
                content: [
                    'Untuk trip 2–3 hari ke pulau, aturan emasnya adalah membawa 1 set pakaian yang sedang dipakai, 1 set pakaian ganti berenang/aktivitas, dan 1 set pakaian santai untuk istirahat malam hari.',
                    'Pilih bahan katun ringan atau linen yang menyerap keringat dengan baik serta mudah kering saat diangin-anginkan di penginapan.',
                ],
                proTip: {
                    title: 'Checklist Cepat Ransel Pantai',
                    items: [
                        'Sunscreen ramah terumbu karang (reef-safe) SPF 50+',
                        'Kacamata hitam terpolarisasi dan topi pelindung',
                        'Sandal gunung tahan air dengan grip yang kuat',
                    ],
                },
            },
        ],
        relatedTrip: {
            title: 'Open Trip Tur Pulau Pramuka & Semak Daun',
            slug: 'pulau-pramuka',
            type: 'open-trip',
            duration: '2H1M',
            price: 'Rp 450.000',
            originalPrice: 'Rp 550.000',
            image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=800&q=84',
            rating: 4.9,
            reviewsCount: 428,
            badge: 'Best Seller',
        },
        initialComments: [
            {
                id: 1,
                name: 'Fahri Alamsyah',
                avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=120&q=80',
                role: 'Weekend Traveler',
                date: '5 hari yang lalu',
                rating: 5,
                content: 'Panduan ini mengubah cara saya packing! Biasanya bawa koper gede, kemarin cuma bawa ransel 28L dan jauh lebih bebas jalan ke mana-mana.',
                likes: 11,
            },
        ],
    },
    {
        id: 'snorkeling',
        category: 'Wisata Alam',
        title: 'Menikmati keindahan laut dengan lebih bertanggung jawab',
        image: '1546026423-cc4642628d2b',
        excerpt: 'Kenali kebiasaan sederhana untuk menjaga terumbu karang dan satwa laut tetap lestari saat snorkeling.',
        body: 'Dengarkan pengarahan pemandu sebelum masuk ke air dan gunakan perlengkapan yang sesuai. Nikmati terumbu karang dari jarak aman tanpa menyentuh atau menginjaknya. Hindari memberi makan satwa laut, bawa kembali sampahmu, dan pilih kegiatan yang sesuai kemampuan berenangmu.',
        date: '2 Sep 2026',
        readTime: '4 menit baca',
        views: '1.7k dibaca',
        location: 'Taman Nasional Komodo & Kepulauan Seribu',
        heroCaption: 'Keanekaragaman hayati terumbu karang dan ikan koral di perairan laut jernih',
        author: {
            name: 'Dr. Gede Mahardika',
            role: 'Marine Biologist & Dive Master',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80',
            bio: 'Meneliti konservasi terumbu karang selama 12 tahun. Berkomitmen mengedukasi wisatawan tentang pentingnya menjaga ekosistem laut.',
            badge: 'Peneliti Konservasi',
            storiesCount: 9,
        },
        quickFacts: {
            bestTime: 'Pagi Hari (08.00 – 11.00)',
            budget: 'Sewa Alat Rp 50.000 – 100.000',
            duration: '2 – 3 Jam Sesi',
            access: 'Kapal sewa lokal',
            language: 'Bahasa Indonesia',
        },
        gallery: [
            'https://images.unsplash.com/photo-1546026423-cc4642628d2b?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=1200&q=88',
            'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=1200&q=88',
        ],
        tags: ['Wisata Bahari', 'Snorkeling', 'Konservasi Laut', 'Terumbu Karang', 'Ekowisata'],
        reactions: {
            helpful: 310,
            inspiring: 195,
            wantToGo: 280,
        },
        sections: [
            {
                id: 'karang-hidup',
                heading: 'Jangan Pernah Menginjak Karang, Mereka Makhluk Hidup',
                content: [
                    'Banyak pemula yang tidak menyadari bahwa terumbu karang adalah koloni hewan laut hidup yang membutuhkan waktu puluhan hingga ratusan tahun untuk tumbuh hanya beberapa sentimeter. Menginjaknya dengan kaki katak (fin) dapat mematahkan struktur dan mematikan koloni tersebut.',
                    'Jika merasa lelah di tengah laut, rilekskan tubuh dalam posisi telentang (floating) dengan bantuan jaket pelampung, alih-alih mencari pijakan karang.',
                ],
                proTip: {
                    title: 'Etika Snorkeling Bertanggung Jawab',
                    items: [
                        'Gunakan tabir surya non-nano zinc oxide (bebas Oxybenzone & Octinoxate).',
                        'Jangan memberi makan roti atau nasi ke ikan karena mengubah perilaku alami mereka.',
                        'Pertahankan jarak minimal 1 meter dari satwa laut seperti penyu dan pari.',
                    ],
                },
            },
        ],
        relatedTrip: {
            title: 'Private Trip Labuan Bajo',
            slug: 'labuan-bajo',
            type: 'private-trip',
            duration: '3H2M',
            price: 'Rp 2.850.000',
            originalPrice: 'Rp 3.250.000',
            image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=84',
            rating: 4.9,
            reviewsCount: 189,
            badge: 'Wisata Bahari Terbaik',
        },
        initialComments: [
            {
                id: 1,
                name: 'Sarah Wijaya',
                avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&q=80',
                role: 'Snorkeler Pemula',
                date: '1 minggu yang lalu',
                rating: 5,
                content: 'Penjelasan yang sangat penting! Banyak yang belum tahu kalau terumbu karang itu hewan hidup yang rapuh. Wajib dibaca sebelum berangkat snorkeling.',
                likes: 24,
            },
        ],
    },
];

export const getArticleById = (id) => {
    return articles.find((article) => article.id === id) || articles[0];
};
