<script setup>
import { computed, ref } from 'vue';
import { BadgeCheck, CalendarDays, ChevronLeft, ChevronRight, Clock3, ExternalLink, Heart, MapPin, Star, Users } from 'lucide-vue-next';

const props = defineProps({ tripType: { type: String, required: true } });
const currentPage = ref(1);
const savedTrips = ref([]);
const pageSize = 3;
const trips = computed(() => props.tripType === 'private-trip' ? [
    { title: 'Private Trip Pulau Kelor 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.450.000', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Sailing Komodo 3H2M', location: 'Labuan Bajo, NTT', duration: '3 Hari 2 Malam', price: '3.750.000', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Pink Beach 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.950.000', image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Pulau Padar 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.750.000', image: 'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Wae Rebo 3H2M', location: 'Manggarai, NTT', duration: '3 Hari 2 Malam', price: '3.250.000', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=85' },
] : [
    { title: 'Open Trip Pulau Tidung 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '375.000', image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Harapan 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '420.000', image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Pari 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '395.000', image: 'https://images.unsplash.com/photo-1505881502353-a1986add3762?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Macan 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '450.000', image: 'https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Pramuka 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '400.000', image: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=900&q=85' },
]);
const pageCount = computed(() => Math.ceil(trips.value.length / pageSize));
const visibleTrips = computed(() => trips.value.slice((currentPage.value - 1) * pageSize, currentPage.value * pageSize));
const toggleSaved = (title) => { savedTrips.value = savedTrips.value.includes(title) ? savedTrips.value.filter((item) => item !== title) : [...savedTrips.value, title]; };
</script>

<template>
    <section class="relative mt-7 overflow-hidden rounded-xl border border-[#e1ebf6] bg-white shadow-[0_6px_18px_rgba(23,75,120,0.04)]" aria-labelledby="recommendation-heading">
        <div class="absolute right-0 top-0 h-52 w-1/2 opacity-60 [background:repeating-radial-gradient(ellipse_at_100%_0%,transparent_0_20px,#d8ecff_21px_22px,transparent_23px_44px)]"></div>
        <header class="relative flex flex-wrap items-center justify-between gap-5 border-b border-[#edf3f8] px-5 py-5 sm:px-6"><div><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1688e8]">Pilihan partner</p><h2 id="recommendation-heading" class="mt-1 text-xl font-extrabold tracking-tight text-[#082d61]">Jelajahi trip lain dari vendor ini</h2><p class="mt-1 text-xs text-[#7186a2]">Temukan lebih banyak pengalaman seru bersama partner terpercaya TapakLokal.</p></div><a href="#" class="group inline-flex items-center gap-2 rounded-full border-2 border-[#b8dcff] bg-white px-4 py-2 text-xs font-extrabold text-[#1688e8] transition-colors duration-200 hover:border-[#1688e8] hover:bg-[#1688e8] hover:text-white hover:shadow-[0_5px_12px_rgba(22,136,232,0.22)]">Lihat semua trip vendor <ChevronRight class="size-4 transition-transform duration-200 group-hover:translate-x-0.5" /></a></header>
        <div class="relative bg-white p-5 sm:p-6">
            <section class="flex flex-wrap items-center gap-4 border-b border-[#e5eef7] pb-5" aria-label="Informasi vendor Brenggo.ID">
                <div class="flex min-w-[190px] flex-1 items-center gap-3"><span class="grid size-12 shrink-0 place-items-center rounded-lg border border-[#e4edf6] bg-white"><img src="/Assets/Images/logo-vendor/logo-brenggo-tour.jpg" alt="Logo Brenggo.ID" class="size-9 object-contain" /></span><div><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-[#1688e8]">Diselenggarakan oleh</p><p class="mt-1 flex items-center gap-1.5 text-lg font-extrabold text-[#082d61]">BRENGGO.ID <BadgeCheck class="size-4 fill-[#1688e8] text-white" /></p><p class="mt-1 text-[11px] text-[#7186a2]">Partner terverifikasi TapakLokal</p><a href="#" class="group mt-2 inline-flex items-center gap-2 rounded-full border-2 border-[#b8dcff] bg-white px-4 py-2 text-xs font-extrabold text-[#1688e8] transition-colors duration-200 hover:border-[#1688e8] hover:bg-[#1688e8] hover:text-white hover:shadow-[0_5px_12px_rgba(22,136,232,0.22)]">Profil vendor <ExternalLink class="size-3.5 transition-transform duration-200 group-hover:translate-x-0.5" /></a></div></div>
                <div class="grid w-full grid-cols-1 divide-y divide-[#e5eef7] rounded-lg border border-[#e5eef7] bg-[#fbfdff] sm:min-w-[300px] sm:flex-1 sm:grid-cols-3 sm:divide-x sm:divide-y-0"><div class="flex min-w-0 items-center gap-2 px-3 py-3"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#fff5db]"><Star class="size-3.5 fill-[#f5a000] text-[#f5a000]" /></span><div class="min-w-0"><p class="whitespace-nowrap text-[11px] font-extrabold text-[#173b70]">4.9 / 5.0</p><p class="mt-0.5 whitespace-nowrap text-[9px] text-[#7186a2]">1.248 ulasan</p></div></div><div class="flex min-w-0 items-center gap-2 px-3 py-3"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#eaf5ff]"><Clock3 class="size-3.5 text-[#1688e8]" /></span><div class="min-w-0"><p class="whitespace-nowrap text-[11px] font-extrabold text-[#173b70]">Balas &lt; 1 jam</p><p class="mt-0.5 whitespace-nowrap text-[9px] text-[#7186a2]">Respons cepat</p></div></div><div class="flex min-w-0 items-center gap-2 px-3 py-3"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#eaf5ff]"><Users class="size-3.5 text-[#1688e8]" /></span><div class="min-w-0"><p class="whitespace-nowrap text-[11px] font-extrabold text-[#173b70]">45 trip aktif</p><p class="mt-0.5 whitespace-nowrap text-[9px] text-[#7186a2]">1.500+ traveler</p></div></div></div>
            </section>
            <div class="mt-5"><div class="mb-3 flex items-center justify-between"><h3 class="text-base font-extrabold text-[#082d61]">Trip yang mungkin kamu suka</h3><span class="text-[10px] font-semibold text-[#60789c]">{{ trips.length }} trip tersedia</span></div><div class="relative"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><article v-for="trip in visibleTrips" :key="trip.title" class="overflow-hidden rounded-lg border border-[#dce9f5] bg-white"><div class="relative h-32 overflow-hidden"><img :src="trip.image" :alt="trip.title" class="size-full object-cover" /><span class="absolute left-3 top-3 rounded-md bg-[#1688e8] px-2.5 py-1 text-[10px] font-bold text-white">{{ tripType === 'private-trip' ? 'Private Trip' : 'Open Trip' }}</span><button type="button" class="absolute right-3 top-3 grid size-8 place-items-center rounded-full bg-white/95 text-[#082d61]" :aria-label="`Simpan ${trip.title}`" @click="toggleSaved(trip.title)"><Heart class="size-4" :class="savedTrips.includes(trip.title) ? 'fill-[#ef4d63] text-[#ef4d63]' : ''" /></button></div><div class="p-3"><h3 class="truncate text-sm font-extrabold text-[#082d61]">{{ trip.title }}</h3><p class="mt-2 flex items-center gap-1.5 text-[11px] text-[#60789c]"><MapPin class="size-3.5 text-[#1688e8]" />{{ trip.location }}</p><p class="mt-1 flex items-center gap-1.5 text-[11px] text-[#60789c]"><CalendarDays class="size-3.5 text-[#1688e8]" />{{ trip.duration }}</p><div class="mt-3 flex items-center justify-between border-t border-[#e7eef5] pt-3"><span class="text-base font-extrabold text-[#082d61]">Rp {{ trip.price }}<small class="ml-1 text-[10px] font-medium text-[#7186a2]">/orang</small></span><button type="button" class="inline-flex items-center gap-1 text-[10px] font-bold text-[#1688e8]">Detail <ChevronRight class="size-3.5" /></button></div></div></article></div><button v-if="currentPage > 1" type="button" class="absolute -left-4 top-1/2 hidden size-10 -translate-y-1/2 place-items-center rounded-full border border-[#dce8f3] bg-white text-[#1688e8] shadow-lg xl:grid" aria-label="Rekomendasi sebelumnya" @click="currentPage -= 1"><ChevronLeft class="size-5" /></button><button type="button" class="absolute -right-4 top-1/2 hidden size-10 -translate-y-1/2 place-items-center rounded-full border border-[#dce8f3] bg-white text-[#1688e8] shadow-lg xl:grid disabled:opacity-40" :disabled="currentPage === pageCount" aria-label="Rekomendasi berikutnya" @click="currentPage += 1"><ChevronRight class="size-5" /></button></div><footer v-if="pageCount > 1" class="mt-4 flex justify-end gap-2"><button v-for="page in pageCount" :key="page" type="button" class="size-2 rounded-full transition-all" :class="currentPage === page ? 'w-6 bg-[#1688e8]' : 'bg-[#c7dcef]'" :aria-label="`Halaman ${page}`" @click="currentPage = page"></button></footer></div>
        </div>    </section>
</template>
