<script setup>
import { computed, ref } from 'vue';
import { CalendarDays, ChevronLeft, ChevronRight, Clock3, Heart, MapPin, Star } from 'lucide-vue-next';

const props = defineProps({ tripType: { type: String, required: true } });
const currentPage = ref(1);
const savedTrips = ref([]);
const pageSize = 4;
const trips = computed(() => props.tripType === 'private-trip' ? [
    { title: 'Private Trip Pulau Kelor 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.450.000', image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Sailing Komodo 3H2M', location: 'Labuan Bajo, NTT', duration: '3 Hari 2 Malam', price: '3.750.000', image: 'https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Pink Beach 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.950.000', image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Pulau Padar 2H1M', location: 'Labuan Bajo, NTT', duration: '2 Hari 1 Malam', price: '2.750.000', image: 'https://images.unsplash.com/photo-1544550285-f813152fb2fd?auto=format&fit=crop&w=900&q=85' },
    { title: 'Private Trip Wae Rebo 3H2M', location: 'Manggarai, NTT', duration: '3 Hari 2 Malam', price: '3.250.000', image: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=900&q=85' },
] : [
    { title: 'Open Trip Pulau Tidung 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '375.000', image: 'https://images.unsplash.com/photo-1516690561799-46d8f74f9abf?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Harapan 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '420.000', image: 'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Pari 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '395.000', image: 'https://images.unsplash.com/photo-1505881502353-a1986add3762?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Macan 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '450.000', image: 'https://images.unsplash.com/photo-1468413253725-0d5181091126?auto=format&fit=crop&w=900&q=85' },
    { title: 'Open Trip Pulau Pramuka 2H1M', location: 'Kepulauan Seribu', duration: '2 Hari 1 Malam', price: '400.000', image: 'https://images.unsplash.com/photo-1540202404-a2f29016b523?auto=format&fit=crop&w=900&q=85' },
]);
const pageCount = computed(() => Math.ceil(trips.value.length / pageSize));
const visibleTrips = computed(() => trips.value.slice((currentPage.value - 1) * pageSize, currentPage.value * pageSize));
const toggleSaved = (title) => { savedTrips.value = savedTrips.value.includes(title) ? savedTrips.value.filter((item) => item !== title) : [...savedTrips.value, title]; };
</script>

<template>
    <section class="mt-7 overflow-hidden rounded-2xl border border-[#dfeaf5] bg-white shadow-[0_10px_28px_rgba(23,75,120,0.05)]" aria-labelledby="recommendation-heading">
        <header class="flex flex-wrap items-center justify-between gap-4 border-b border-[#e8f0f7] px-5 py-5 sm:px-7"><div><p class="text-[10px] font-bold uppercase tracking-[0.16em] text-[#1688e8]">Pilihan partner</p><h2 id="recommendation-heading" class="mt-1 text-xl font-extrabold tracking-tight text-[#173b70]">Jelajahi trip lain dari vendor ini</h2></div><a href="#" class="group inline-flex items-center gap-1 text-xs font-bold text-[#1688e8]">Semua trip vendor <ChevronRight class="size-4 transition-transform group-hover:translate-x-0.5" /></a></header>
        <div class="grid gap-5 p-5 sm:p-6 xl:grid-cols-[250px_minmax(0,1fr)]"><aside class="self-start overflow-hidden rounded-xl border border-[#d6eafb] bg-[#f1f8ff]"><div class="border-b border-[#d6eafb] px-5 py-4"><p class="text-[10px] font-bold uppercase tracking-[0.14em] text-[#1688e8]">Diselenggarakan oleh</p><div class="mt-3 flex items-center gap-3"><span class="grid size-12 place-items-center rounded-xl bg-white shadow-[0_4px_12px_rgba(37,119,192,0.10)]"><img src="/Assets/Images/logo-vendor/logo-brenggo-tour.jpg" alt="Logo Brenggo.ID" class="size-9 object-contain" /></span><div><p class="text-base font-extrabold"><span class="text-[#ef2f36]">BRENGGO</span><span class="text-[#173b70]">.ID</span></p><p class="mt-0.5 text-[10px] font-semibold text-[#60789c]">Partner terverifikasi TapakLokal</p></div></div></div><div class="px-5 py-4"><p class="text-xs font-extrabold text-[#173b70]">Informasi partner</p><div class="mt-3 grid grid-cols-2 gap-2"><div class="min-w-0 rounded-lg border border-[#dbeaf7] bg-white px-2.5 py-2.5"><div class="flex items-center gap-2"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#fff5d9] text-[#ee9c00]"><Star class="size-3.5 fill-current" /></span><p class="truncate text-[10px] font-extrabold text-[#173b70]">4.9 / 5.0</p></div><p class="mt-1 truncate text-[10px] font-semibold text-[#7186a2]">1.248 ulasan</p></div><div class="min-w-0 rounded-lg border border-[#dbeaf7] bg-white px-2.5 py-2.5"><div class="flex items-center gap-2"><span class="grid size-7 shrink-0 place-items-center rounded-full bg-[#e8f4ff] text-[#1688e8]"><Clock3 class="size-3.5" /></span><p class="truncate text-[10px] font-extrabold text-[#173b70]">Respons cepat</p></div><p class="mt-1 truncate text-[10px] font-semibold text-[#7186a2]">Balas &lt; 1 jam</p></div></div></div></aside>
            <div class="min-w-0"><div class="mb-3 flex items-center justify-between"><p class="text-xs font-extrabold text-[#173b70]">Trip yang mungkin kamu suka</p><span class="text-[10px] font-semibold text-[#7186a2]">{{ trips.length }} trip tersedia</span></div><div class="relative"><div class="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><article v-for="trip in visibleTrips" :key="trip.title" class="overflow-hidden rounded-xl border border-[#e1ebf6] bg-white"><div class="relative h-28 overflow-hidden"><img :src="trip.image" :alt="trip.title" class="size-full object-cover" /><span class="absolute inset-0 bg-gradient-to-t from-[#071a32]/30 via-transparent to-transparent"></span><span class="absolute bottom-2 left-2 rounded-full bg-[#1688e8] px-2.5 py-1 text-[9px] font-bold text-white">{{ tripType === 'private-trip' ? 'Private Trip' : 'Open Trip' }}</span><button type="button" class="absolute right-2 top-2 grid size-8 place-items-center rounded-full bg-white/90 text-[#173b70]" :aria-label="`Simpan ${trip.title}`" @click="toggleSaved(trip.title)"><Heart class="size-4" :class="savedTrips.includes(trip.title) ? 'fill-[#ef4d63] text-[#ef4d63]' : ''" /></button></div><div class="p-3"><h3 class="truncate text-xs font-extrabold text-[#173b70]">{{ trip.title }}</h3><p class="mt-2 flex items-center gap-1 text-[10px] text-[#7186a2]"><MapPin class="size-3 text-[#1688e8]" />{{ trip.location }}</p><p class="mt-1 flex items-center gap-1 text-[10px] text-[#7186a2]"><CalendarDays class="size-3 text-[#1688e8]" />{{ trip.duration }}</p><div class="mt-3 flex items-baseline gap-1"><span class="text-sm font-extrabold text-[#173b70]">Rp {{ trip.price }}</span><span class="text-[9px] text-[#8aa0ba]">/orang</span></div></div></article></div><button v-if="currentPage > 1" type="button" class="absolute -left-4 top-1/2 hidden size-10 -translate-y-1/2 place-items-center rounded-full border border-[#dce8f3] bg-white text-[#1688e8] shadow-lg xl:grid" aria-label="Rekomendasi sebelumnya" @click="currentPage -= 1"><ChevronLeft class="size-5" /></button><button type="button" class="absolute -right-4 top-1/2 hidden size-10 -translate-y-1/2 place-items-center rounded-full border border-[#dce8f3] bg-white text-[#1688e8] shadow-lg xl:grid disabled:opacity-40" :disabled="currentPage === pageCount" aria-label="Rekomendasi berikutnya" @click="currentPage += 1"><ChevronRight class="size-5" /></button></div><footer v-if="pageCount > 1" class="mt-4 flex justify-end gap-2"><button v-for="page in pageCount" :key="page" type="button" class="h-2 rounded-full transition-all" :class="currentPage === page ? 'w-6 bg-[#1688e8]' : 'w-2 bg-[#c7d9ea]'" :aria-label="`Halaman ${page}`" @click="currentPage = page"></button></footer></div>
        </div>
    </section>
</template>
