<script setup>
import { Link, router, usePage } from '@inertiajs/vue3';
import PanelLayout from '../../Components/Admin/PanelLayout.vue';
import { ArrowUpRight, CheckCircle2, Clock3 } from 'lucide-vue-next';
defineProps({ navigation: Array, stats: Array, alerts: Array, activity: Array, gatewayReady: Boolean, panelLabel: String, panelDescription: String, reportDays: Number, bookingReport: Array });
const page = usePage();
const money = value => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(value);
</script>
<template>
    <PanelLayout :title="page.props.adminPanel?.key === 'super' ? 'Laporan & Pengawasan' : panelLabel" :subtitle="panelDescription" :navigation="navigation">
        <section v-if="page.props.adminPanel?.key === 'super'" class="mb-7 flex flex-wrap gap-3"><Link v-for="panel in page.props.adminPanel.available.filter(item => item.key !== 'super')" :key="panel.key" :href="panel.url" class="panel-secondary">Buka {{ panel.label }}<ArrowUpRight class="size-4" /></Link></section>
        <div class="mb-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><article v-for="stat in stats" :key="stat.label" class="rounded-2xl border border-slate-200/70 bg-white p-5"><p class="text-xs font-medium text-slate-500">{{ stat.label }}</p><p class="mt-4 text-3xl font-bold tracking-tight text-[#17345e]">{{ stat.money ? money(stat.value) : stat.value }}</p><p class="mt-3 text-[11px] text-slate-400">{{ stat.hint }}</p></article></div>
        <section v-if="['super', 'finance'].includes(page.props.adminPanel?.key)" class="panel-surface mb-7"><div class="flex flex-wrap items-center justify-between gap-3 border-b border-slate-100 p-5"><div><h2 class="text-sm font-bold">Laporan pemesanan</h2><p class="mt-1 text-xs text-slate-500">Nilai pesanan berdasarkan status, bukan seluruhnya pendapatan yang sudah diterima.</p></div><select :value="reportDays" aria-label="Periode laporan" class="panel-input w-auto" @change="router.get(page.props.adminPanel.url, { days: $event.target.value }, { preserveScroll: true })"><option :value="7">7 hari</option><option :value="30">30 hari</option><option :value="90">90 hari</option></select></div><div class="overflow-x-auto"><table class="w-full text-left text-xs"><thead class="bg-slate-50 text-slate-500"><tr><th class="p-4">Status</th><th class="p-4">Pesanan</th><th class="p-4">Nilai total</th><th class="p-4">Porsi platform</th><th class="p-4">Porsi vendor</th></tr></thead><tbody><tr v-for="row in bookingReport" :key="row.status" class="border-t border-slate-100"><td class="p-4">{{ row.status }}</td><td class="p-4">{{ row.bookings }}</td><td class="p-4">{{ money(row.total) }}</td><td class="p-4">{{ money(row.platform_fee) }}</td><td class="p-4">{{ money(row.vendor_amount) }}</td></tr></tbody></table><p v-if="!bookingReport.length" class="p-8 text-center text-sm text-slate-400">Belum ada pemesanan dalam periode ini.</p></div></section>
        <div class="grid gap-6" :class="page.props.adminPanel?.key === 'super' ? 'xl:grid-cols-[1.2fr_1fr]' : ''">
            <section class="panel-surface"><div class="border-b border-slate-100 p-5"><h2 class="text-sm font-bold">Perlu perhatian</h2><p class="mt-1 text-xs text-slate-400">Antrean kerja sesuai akses kamu</p></div><Link v-for="alert in alerts" :key="alert.label" :href="alert.url" class="flex items-center gap-3 border-b border-slate-50 px-5 py-4 last:border-0 hover:bg-blue-50/40"><span class="grid size-9 place-items-center rounded-xl" :class="alert.count ? 'bg-amber-50 text-amber-600' : 'bg-emerald-50 text-emerald-600'"><Clock3 v-if="alert.count" class="size-4" /><CheckCircle2 v-else class="size-4" /></span><span class="flex-1 text-sm font-medium">{{ alert.label }}</span><span class="rounded-lg bg-slate-100 px-2 py-1 text-xs font-semibold">{{ alert.count }}</span><ArrowUpRight class="size-4 text-slate-400" /></Link><p v-if="!alerts.length" class="p-8 text-center text-sm text-slate-400">Tidak ada antrean untuk peran ini.</p></section>
            <section v-if="page.props.adminPanel?.key === 'super'" class="panel-surface"><div class="border-b border-slate-100 p-5"><h2 class="text-sm font-bold">Aktivitas terbaru</h2><p class="mt-1 text-xs text-slate-400">Jejak tindakan pada platform</p></div><div v-for="item in activity" :key="item.id" class="flex items-start gap-3 px-5 py-4"><span class="mt-1.5 size-2 rounded-full bg-blue-400"></span><div><p class="text-xs font-semibold">{{ item.action }}</p><p class="mt-1 text-xs text-slate-400">{{ item.user?.name || 'Sistem' }} · {{ new Date(item.created_at).toLocaleString('id-ID') }}</p></div></div><p v-if="!activity.length" class="p-8 text-center text-sm text-slate-400">Belum ada aktivitas yang dapat ditampilkan.</p></section>
        </div>
        <div v-if="!gatewayReady" class="mt-6 rounded-xl border border-amber-100 bg-amber-50 px-5 py-4 text-xs leading-6 text-amber-800">Pembayaran online belum aktif. Pesanan tetap dapat dicatat, tetapi pembayaran dan pencairan tidak akan ditandai berhasil tanpa konfirmasi gateway.</div>
    </PanelLayout>
</template>
