<script setup>
import { computed, ref } from 'vue';
import { Link, useForm, usePage } from '@inertiajs/vue3';
import { route } from 'ziggy-js';
import Pagination from '../Admin/Pagination.vue';
const page = usePage();
const section = computed(() => page.props.sectionKey);
const records = computed(() => page.props.records);
const form = useForm({ name: '', birth_date: '', phone: '', emergency_contact: '' });
const travelerId = ref(null);
const showTraveler = ref(false);
const profile = useForm({ name: page.props.auth.user.name, phone: page.props.auth.user.phone || '', city: page.props.auth.user.city || '' });
const password = useForm({ current_password: '', password: '', password_confirmation: '' });
const ticket = useForm({ subject: '', category: 'booking', body: '', booking_id: '' });
const review = useForm({ booking_id: '', rating: 5, body: '' });
const money = n => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n);
const editTraveler = item => { travelerId.value = item?.id || null; form.name = item?.name || ''; form.birth_date = item?.birth_date?.slice(0,10) || ''; form.phone = item?.phone || ''; form.emergency_contact = item?.emergency_contact || ''; showTraveler.value = true; };
const saveTraveler = () => travelerId.value ? form.patch(route('travelers.update', travelerId.value), { onSuccess: () => showTraveler.value = false }) : form.post(route('travelers.store'), { onSuccess: () => showTraveler.value = false });
</script>
<template>
    <div>
        <div class="mb-5 flex items-center justify-between gap-3"><div><h2 class="text-base font-bold text-[#183660]">{{ page.props.sectionLabel }}</h2><p class="mt-1 text-xs text-slate-400">Kelola aktivitas dan informasi perjalananmu.</p></div><Link :href="route('catalog')" class="panel-secondary">Jelajahi trip</Link></div>
        <p v-if="page.props.flash?.success" role="status" class="mb-4 rounded-lg bg-emerald-50 p-3 text-xs text-emerald-700">{{ page.props.flash.success }}</p><p v-for="(error, key) in page.props.errors" :key="key" role="alert" class="mb-3 text-xs text-rose-600">{{ error }}</p>
        <div v-if="section === 'points'" class="mb-5 rounded-2xl bg-[#3e7bef] p-6 text-white"><p class="text-xs text-blue-100">Tapak Points tersedia</p><p class="mt-3 text-4xl font-bold">{{ page.props.pointBalance }}</p><p class="mt-3 text-xs text-blue-100">Poin diperoleh dari perjalanan selesai dan tercatat pada riwayat.</p></div>
        <p v-if="section === 'wallet'" class="mb-5 rounded-xl bg-blue-50 p-4 text-xs leading-6 text-blue-700">Pembayaran dikelola melalui gateway pada masing-masing pesanan. Tapak Lokal belum menyediakan saldo tersimpan atau penyimpanan data kartu.</p>
        <div v-if="section === 'settings'" class="space-y-5">
            <form class="panel-surface p-5" @submit.prevent="profile.patch(route('account.profile'))"><h3 class="mb-5 text-sm font-bold">Data pribadi</h3><div class="grid gap-4 sm:grid-cols-2"><label v-for="(label, key) in { name: 'Nama lengkap', phone: 'Nomor ponsel', city: 'Kota' }" :key="key" class="text-xs font-semibold">{{ label }}<input v-model="profile[key]" :required="key === 'name'" class="panel-input mt-2" /></label></div><button :disabled="profile.processing" class="panel-primary mt-5">Simpan profil</button></form>
            <form class="panel-surface p-5" @submit.prevent="password.put(route('account.password'), { onSuccess: () => password.reset() })"><h3 class="mb-5 text-sm font-bold">Keamanan akun</h3><div class="grid gap-4"><label v-for="(label, key) in { current_password: 'Kata sandi saat ini', password: 'Kata sandi baru', password_confirmation: 'Konfirmasi kata sandi baru' }" :key="key" class="text-xs font-semibold">{{ label }}<input v-model="password[key]" type="password" :autocomplete="key === 'current_password' ? 'current-password' : 'new-password'" required class="panel-input mt-2" /></label></div><p class="mt-3 text-xs text-slate-400">Minimal 10 karakter, berisi huruf dan angka.</p><button :disabled="password.processing" class="panel-primary mt-5">Ubah kata sandi</button></form>
        </div>
        <template v-if="section === 'travelers'"><button class="panel-primary mb-4" @click="editTraveler(null)">Tambah wisatawan</button><form v-if="showTraveler" class="panel-surface mb-5 p-5" @submit.prevent="saveTraveler"><div class="grid gap-4 sm:grid-cols-2"><label v-for="(label, key) in { name: 'Nama lengkap', birth_date: 'Tanggal lahir', phone: 'Nomor kontak', emergency_contact: 'Kontak darurat' }" :key="key" class="text-xs font-semibold">{{ label }}<input v-model="form[key]" :type="key === 'birth_date' ? 'date' : 'text'" :required="key === 'name'" class="panel-input mt-2" /></label></div><button :disabled="form.processing" class="panel-primary mt-4">Simpan wisatawan</button><button type="button" class="panel-secondary ml-2" @click="showTraveler = false">Batal</button></form></template>
        <form v-if="['support', 'chat'].includes(section)" class="panel-surface mb-5 p-5" @submit.prevent="ticket.post(route('support.store'))"><h3 class="mb-4 text-sm font-bold">Mulai percakapan</h3><div class="grid gap-4 sm:grid-cols-2"><input v-model="ticket.subject" required placeholder="Subjek" aria-label="Subjek" class="panel-input" /><select v-model="ticket.category" aria-label="Kategori" class="panel-input"><option value="booking">Pemesanan</option><option value="payment">Pembayaran</option><option value="account">Akun</option><option value="vendor">Hubungi vendor</option><option value="other">Lainnya</option></select><input v-model="ticket.booking_id" type="number" placeholder="ID pesanan terkait (opsional)" aria-label="ID pesanan" class="panel-input" /><textarea v-model="ticket.body" required minlength="10" placeholder="Ceritakan kebutuhanmu…" aria-label="Pesan" rows="3" class="panel-input sm:col-span-2"></textarea></div><button :disabled="ticket.processing" class="panel-primary mt-4">Kirim pesan</button></form>
        <form v-if="section === 'reviews' && page.props.reviewable.length" class="panel-surface mb-5 p-5" @submit.prevent="review.post(route('reviews.store'), { onSuccess: () => review.reset() })"><h3 class="mb-4 text-sm font-bold">Bagikan pengalaman perjalanan</h3><select v-model="review.booking_id" required class="panel-input" aria-label="Pilih perjalanan"><option disabled value="">Pilih perjalanan selesai</option><option v-for="booking in page.props.reviewable" :key="booking.id" :value="booking.id">{{ booking.trip.title }} · {{ booking.reference }}</option></select><label class="mt-4 block text-xs">Rating<select v-model="review.rating" class="panel-input mt-2"><option v-for="n in 5" :key="n" :value="n">{{ n }} bintang</option></select></label><textarea v-model="review.body" required minlength="10" rows="3" class="panel-input mt-4" placeholder="Bagaimana perjalananmu?" aria-label="Ulasan"></textarea><button :disabled="review.processing" class="panel-primary mt-4">Kirim ulasan</button></form>
        <section v-if="records" class="panel-surface">
            <article v-for="item in records.data" :key="item.id" class="flex flex-wrap items-center gap-4 border-b border-slate-100 p-4">
                <img v-if="item.trip?.image_url" :src="item.trip.image_url" :alt="item.trip.title" loading="lazy" class="h-20 w-28 rounded-xl object-cover" />
                <div class="min-w-0 flex-1"><p class="text-sm font-bold text-[#183660]">{{ item.trip?.title || item.name || item.subject || item.reference || item.description }}</p><p v-if="item.reference" class="mt-1 text-[10px] text-slate-400">{{ item.reference }}</p><p class="mt-2 whitespace-pre-wrap text-xs leading-5 text-slate-500">{{ item.body || item.phone || item.status || item.code || item.description }}</p><p v-if="item.total || item.amount" class="mt-2 text-sm font-semibold text-blue-600">{{ money(item.total || item.amount) }}</p><p v-if="item.points !== undefined" class="mt-2 text-sm font-bold" :class="item.points < 0 ? 'text-rose-500' : 'text-emerald-600'">{{ item.points > 0 ? '+' : '' }}{{ item.points }} points</p><p v-if="section === 'vouchers'" class="mt-2 text-xs text-blue-600">Kode {{ item.code }} · {{ item.type === 'percent' ? item.value + '%' : money(item.value) }} · minimum {{ money(item.minimum_amount) }}</p><p v-if="item.rating" class="mt-2 text-xs text-amber-600">{{ item.rating }} / 5 bintang</p></div>
                <div class="flex gap-2"><Link v-if="section === 'bookings'" :href="route('bookings.show', item.id)" class="panel-secondary">Detail & tiket</Link><Link v-if="['transactions', 'wallet'].includes(section)" :href="route('bookings.show', item.booking_id)" class="panel-secondary">Detail</Link><Link v-if="['chat', 'support'].includes(section)" :href="route('support.show', item.id)" class="panel-secondary">Buka</Link><button v-if="section === 'travelers'" class="panel-secondary" @click="editTraveler(item)">Edit</button><Link v-if="section === 'travelers'" :href="route('travelers.destroy', item.id)" method="delete" as="button" class="panel-secondary">Hapus</Link><Link v-if="section === 'favorites'" :href="route('favorites.destroy', item.id)" method="delete" as="button" class="panel-secondary">Hapus favorit</Link></div>
            </article>
            <div v-if="!records.data.length" class="px-5 py-12 text-center"><p class="text-sm font-semibold text-slate-500">Belum ada data</p><p class="mt-2 text-xs text-slate-400">Aktivitasmu akan muncul di sini setelah tersimpan.</p></div><Pagination :records="records" />
        </section>
    </div>
</template>

